export default {
    "2": { "categoría": 3 },
    "3": { "marca": 1, "modelo": 1 },
    "23": { "deporte": 1 },
    "310": { "marca": 1 },
    "360": { "marca": 1 },
    "502": { "marca": 1 },
    "Pantalón": { "categoría": 134 },
    "cuadros": { "cuadros": 1, "marca": 1 },
    "bi-stretch": { "bi-stretch": 1 },
    "slim": {
      "modelo": 4,
      "largo": 2,
      "slim": 2,
      "ancho": 1,
      "tipo": 1,
      "básico": 1,
      "tamaño": 1
    },
    "Vaquero": { "marca": 2, "categoría": 6 },
    "™": { "marca": 2 },
    "Taper": { "modelo": 1 },
    "vaquero": { "vaquero": 1, "deporte": 2, "categoría": 1, "marca": 1 },
    "Vila": { "marca": 4 },
    "Skinny": { "modelo": 3, "talle": 1 },
    "fit": {
      "modelo": 6,
      "tipo": 2,
      "fit": 4,
      "ancho": 1,
      "básico": 1,
      "tamaño": 1
    },
    "New": { "marca": 4, "modelo": 1 },
    "Balance": { "marca": 3 },
    "Combat": { "modelo": 2 },
    "Cargo": { "modelo": 13, "tipo de pantalón": 2, "tela": 1, "categoría": 1 },
    "Pants": { "categoría": 34 },
    "jogger": { "modelo": 1 },
    "metálico": { "material": 1 },
    "plata": { "color": 1 },
    "Fred": { "marca": 1 },
    "Perry": { "marca": 1 },
    "Classic": { "modelo": 1 },
    "Swim": { "modelo": 1 },
    "Pantalones": { "categoría": 13 },
    "cortos": { "largo": 4 },
    "adidas": { "marca": 30 },
    "Originals": { "marca": 4 },
    "Adicolor": { "color": 8 },
    "Classics": { "modelo": 6 },
    "Adibreak": { "deporte": 3 },
    "Under": { "marca": 1 },
    "Armour": { "marca": 2 },
    "UA": { "marca": 1 },
    "Fleece": { "marca": 2, "material": 3, "modelo": 2, "categoría": 3 },
    "Track": { "modelo": 20, "deporte": 2, "marca": 1 },
    "Junior": { "edad": 5, "género": 9 },
    "Castore": { "marca": 2 },
    "Wolverhampton": { "deporte": 1 },
    "Wanderers": { "deporte": 1 },
    "Training": { "modelo": 3, "deporte": 4 },
    "Jnr": { "tamaño": 1 },
    "chino": { "modelo": 7, "chino": 1, "género": 1 },
    "PANTALÓN": { "categoría": 52 },
    "TRAINING": { "deporte": 8 },
    "TENTH": { "marca": 17, "deporte": 4, "género": 1 },
    "COSTURA": { "modelo": 1 },
    "DELANTERA": { "talle": 1 },
    "MUJER": { "género": 9 },
    "Vaqueros": { "categoría": 8 },
    "true": { "marca": 3 },
    "cropped": { "largo": 4, "modelo": 1, "corto": 1 },
    "CASUAL": { "categoría": 14, "modelo": 1, "clase": 1 },
    "TEXTURAS": { "marca": 1, "modelo": 1 },
    "HOMBRE": { "género": 27 },
    "terciopelo": { "terciopelo": 1 },
    "negro": { "color": 14, "negro": 1, "modelo": 1 },
    "Jeans": { "categoría": 25, "marca": 1 },
    "Kick": { "modelo": 5 },
    "Flare": { "modelo": 5 },
    "Lavado": { "modelo": 2, "lavado": 3, "tamaño": 1, "talle": 1 },
    "Sostenible": { "marca": 4, "sustentabilidad": 3 },
    "fluido": { "fluido": 5 },
    "estampado": { "estampado": 4, "marca": 1 },
    "geométrico": { "geométrico": 1 },
    "Pack": { "categoría": 3 },
    "de": { "categoría": 10, "deporte": 3, "detalle": 1, "marca": 1 },
    "pantalones": { "categoría": 6 },
    "tipo": { "tipo": 2 },
    "bóxer": { "deporte": 1 },
    "con": { "deporte": 1, "categoría": 2 },
    "corazones": { "deporte": 1 },
    "PANTALON": { "categoría": 19 },
    "DEPORTIVO": { "deportivo": 9 },
    "NIKE": { "marca": 8 },
    "CLUB": { "modelo": 3, "deporte": 1 },
    "NIÑO": { "género": 8, "edad": 10 },
    "culotte": { "culotte": 1 },
    "tiro": { "tiro": 2 },
    "alto": { "alto": 2 },
    "ondas": { "marca": 1 },
    "FÚTBOL": { "deporte": 9 },
    "ACADEMY": { "modelo": 2 },
    "pana": { "pana": 4, "deporte": 2, "modelo": 1, "color": 1, "marca": 1 },
    "cinturón": { "cinturón": 2 },
    "The": { "marca": 5 },
    "North": { "marca": 5 },
    "Face": { "modelo": 5 },
    "Mountain": { "deporte": 1, "modelo": 1 },
    "Athletics": { "deporte": 1, "modelo": 1 },
    "Woven": { "tela": 3, "tipo de pantalón": 6 },
    "punto": { "punto": 3 },
    "beige": { "color": 6 },
    "rectos": { "rectos": 2 },
    "Wedgie": { "marca": 2 },
    "térmico": { "térmico": 1 },
    "interior": { "interior": 1 },
    "lana": { "lana": 1 },
    "merina": { "deporte": 1 },
    "esquí": { "deporte": 2 },
    "y": { "deporte": 1, "categoría": 3 },
    "nieve": { "deporte": 1 },
    "Hombre": { "género": 18 },
    "Wedze": { "marca": 1 },
    "BL900": { "modelo": 1 },
    "FEELCOZY": { "marca": 1 },
    "Jeggings": { "categoría": 1 },
    "Legging": { "categoría": 1 },
    "Evoked": { "marca": 1 },
    "by": { "marca": 1 },
    "corto": { "largo": 4 },
    "Short": { "modelo": 2 },
    "Adidas": { "marca": 15 },
    "OWN": { "marca": 1 },
    "THE": { "marca": 1 },
    "RUN": { "deporte": 1 },
    "Puma": { "marca": 14 },
    "Ess": { "marca": 2 },
    "Slim": { "tamaño": 3, "modelo": 1, "talle": 1 },
    "Ned": { "modelo": 1 },
    "Gray": { "color": 1 },
    "Heather": { "color": 1 },
    "Gris": { "color": 6 },
    "corte": { "corte": 1 },
    "ancho": { "ancho": 6 },
    "Technicals": { "categoría": 1 },
    "Volta": { "deporte": 1 },
    "Supply": { "marca": 4 },
    "&": { "marca": 4 },
    "Demand": { "marca": 4 },
    "Indi": { "categoría": 1 },
    "Joggers": { "modelo": 5, "categoría": 18, "tendencia": 1 },
    "regular": { "regular": 5, "modelo": 2, "tamaño": 1 },
    "lavado": { "lavado": 5, "tipo de lavado": 1, "modelo": 1 },
    "oscuro": { "oscuro": 2, "color": 1 },
    "Pantalon": { "categoría": 10 },
    "Chándal": { "chándal": 1 },
    "Rayas": { "color": 1 },
    "Azul": { "color": 6 },
    "marine": { "color": 3, "modelo": 1 },
    "CORTO": { "largo": 2 },
    "ORIGIN": { "origen": 2, "marca": 2 },
    "JUNIOR": { "edad": 6, "género": 1 },
    "PÁDELPERSONALIZABLE": { "marca": 2 },
    "chinos": { "modelo": 2, "género": 1 },
    "elásticos": { "material": 3 },
    "skinny": { "tipo de pantalón": 2, "modelo": 3, "tipo": 2 },
    "medio": { "tipo de lavado": 1 },
    "ensuciado": { "tipo de lavado": 1, "ensuciado": 1 },
    "Reebok": { "marca": 2 },
    "Wide": { "ancho": 1, "larga": 1, "largo": 1 },
    "Leg": { "largo": 1, "talle": 1 },
    "encerado": { "tipo": 1, "encerado": 1, "efecto": 1 },
    "Botines": { "categoría": 1 },
    "vaqueros": { "deporte": 1, "categoría": 1 },
    "bolsillos": { "bolsillos": 3 },
    "cargo": { "cargo": 6, "deporte": 3 },
    "verde": { "color": 7 },
    "kaki": { "color": 7 },
    "chándal": { "categoría": 2, "chándal": 1 },
    "bajos": { "categoría": 1 },
    "ajustados": { "categoría": 1 },
    "McKenzie": { "marca": 4 },
    "Moran": { "marca": 1 },
    "Poly": { "material": 2 },
    "PUMA": { "marca": 3 },
    "EVOSTRIPE": { "marca": 1 },
    "lurex": { "lurex": 1 },
    "dorado": { "dorado": 1 },
    "Jean": { "categoría": 7 },
    "superestrecho": { "superestrecho": 4 },
    "Mile": { "modelo": 4 },
    "High": { "marca": 4 },
    "Hoodrich": { "marca": 6 },
    "Area": { "categoría": 2 },
    "LOGO": { "marca": 3 },
    "NIÑA": { "género": 3, "edad": 1 },
    "Manchester": { "deporte": 1, "ciudad": 2 },
    "United": { "deporte": 2 },
    "DNA": { "marca": 1 },
    "bandas": { "marca": 1, "modelo": 1 },
    "Tenth": { "marca": 8, "modelo": 4, "deporte": 2 },
    "CANALE": { "cremallera": 1 },
    "CREMALLERAS": { "deporte": 1 },
    "camel": { "color": 2, "modelo": 1 },
    "tapered": { "tapered": 2 },
    "NEW": { "marca": 1 },
    "BALANCE": { "marca": 1 },
    "Super": { "categoría": 1 },
    "leg": { "largo": 1 },
    "pitillo": { "modelo": 2, "tipo": 2 },
    "clásicos": { "modelo": 1 },
    "Champion": { "marca": 2 },
    "LEGACY": { "marca": 1 },
    "AMERICAN": { "marca": 1 },
    "TAPE": { "marca": 3 },
    "NEGRO": { "color": 2 },
    "Pana": { "marca": 3 },
    "Newcastle": { "deporte": 1 },
    "FC": { "deporte": 3, "equipo": 2 },
    "Travel": { "modelo": 1 },
    "Baloncesto": { "deporte": 1 },
    "Tarmak": { "marca": 1 },
    "SH900": { "modelo": 1 },
    "Chino": { "género": 3, "marca": 2, "categoría": 2 },
    "comfort": { "modelo": 2 },
    "knit": { "modelo": 1 },
    "estructura": { "estructura": 1 },
    "Jordan": { "marca": 3 },
    "Paris": { "departamento": 1 },
    "Saint": { "departamento": 1 },
    "Germain": { "departamento": 1 },
    "SST": { "modelo": 1, "marca": 2 },
    "básico": { "básico": 4, "modelo": 1 },
    "cordón": { "cordón": 5 },
    "ESTRECHO": { "deporte": 1 },
    "3S": { "marca": 1, "modelo": 1, "tamaño": 1, "talle": 1 },
    "FL": { "marca": 1 },
    "TC": { "marca": 1 },
    "PT": { "marca": 1, "modelo": 1 },
    "PUNTO": { "deporte": 1, "marca": 1 },
    "ALGODÓN": { "deporte": 1 },
    "Nike": { "marca": 13 },
    "Academy": { "marca": 1 },
    "Therma-FIT": { "marca": 1 },
    "Casual": { "modelo": 7, "categoría": 4, "casual": 1 },
    "Legacy": { "modelo": 1 },
    "ESS": { "modelo": 1, "marca": 2 },
    "fondo": { "deporte": 1 },
    "INOVIK": { "marca": 1 },
    "XC": { "modelo": 1 },
    "S500": { "tamaño": 1 },
    "hOMBRE": { "color": 1 },
    "PIRATA": { "marca": 1 },
    "MONTIREX": { "marca": 2 },
    "Fly": { "marca": 2 },
    "2.0": { "modelo": 1 },
    "ESS+TAPE": { "marca": 1 },
    "SWEATPANTS": { "modelo": 2 },
    "BLANCO": { "color": 1 },
    "pantalón": { "categoría": 3 },
    "reebok": { "marca": 1 },
    "identity": { "marca": 1 },
    "french": { "marca": 1 },
    "terry": { "marca": 1 },
    "ALGODON": { "marca": 1 },
    "Estampado": { "marca": 1 },
    "efecto": { "efecto": 4 },
    "moldeador": { "marca": 2 },
    "Fitness": { "fitness": 1, "deporte": 1 },
    "Cardio": { "cardio": 1 },
    "Sereno": { "modelo": 4, "marca": 2 },
    "Beckenbauer": { "deporte": 3 },
    "SEAM": { "marca": 1 },
    "Logo": { "marca": 5 },
    "Leggins": { "categoría": 1 },
    "detalle": { "detalle": 2 },
    "costuras": { "costuras": 1 },
    "JUICY": { "marca": 1 },
    "COUTURE": { "marca": 1 },
    "Diamante": { "marca": 1 },
    "Velour": { "marca": 2 },
    "FLARE": { "marca": 1 },
    "CR": { "equipo": 1 },
    "Flamengo": { "equipo": 1 },
    "Teamgeist": { "modelo": 1 },
    "Duffer": { "marca": 1 },
    "of": { "marca": 1 },
    "St": { "modelo": 1 },
    "George": { "modelo": 1 },
    "Standard": { "modelo": 2 },
    "Jogging": { "modelo": 1 },
    "Children": { "edad": 1 },
    "premium": { "premium": 1, "categoría": 1 },
    "flex": { "flexibilidad": 1, "categoría": 1 },
    "Tape": { "tape": 1 },
    "Techfleece": { "marca": 1 },
    "Bicolor": { "color": 2 },
    "EXCLUSIVO": { "modelo": 1 },
    "DECIMAS": { "modelo": 1 },
    "ESSENTIALS": { "modelo": 1 },
    "COLORBLOCK": { "modelo": 1, "marca": 1 },
    "FLEECE": { "modelo": 1, "material": 1, "marca": 1 },
    "ADULTO": { "edad": 4 },
    "Tommy": { "marca": 2 },
    "3-Pack": { "modelo": 1 },
    "Lace": { "tela": 1 },
    "Thongs": { "tela": 1 },
    "ADIDAS": { "marca": 6 },
    "CON20": { "modelo": 1 },
    "tachas": { "tachas": 1 },
    "gris": { "color": 6 },
    "antracita": { "color": 3 },
    "Deportivo": { "deportivo": 3 },
    "Básico": { "modelo": 1 },
    "Niña": { "género": 2 },
    "PITILLO": { "talle": 4 },
    "PÁDEL": { "deporte": 6 },
    "Fútbol": { "deporte": 4 },
    "Tiro": { "modelo": 2, "deporte": 1 },
    "Niño": { "género": 10 },
    "/": { "color": 4 },
    "Blanco": { "color": 5 },
    "Byrant": { "modelo": 1 },
    "Push": { "modelo": 1, "deporte": 2, "marca": 1 },
    "up": { "modelo": 1, "tipo": 1, "deporte": 1 },
    "TIE": { "marca": 1 },
    "DYE": { "marca": 1 },
    "Straight": { "estilo": 1 },
    "MERCIER": { "marca": 1 },
    "Kansas": { "modelo": 1 },
    "NBA": { "marca": 1 },
    "York": { "marca": 1 },
    "Knicks": { "marca": 1 },
    "Swingman": { "modelo": 1 },
    "Cortos": { "largo": 1 },
    "Comfort": { "marca": 1 },
    "Yoga": { "marca": 1, "deporte": 1 },
    "Embarazada": { "marca": 1, "género": 1 },
    "Ecofriendly": { "marca": 2 },
    "wide": { "largo": 1 },
    "shorts": { "modelo": 1 },
    "golf": { "deporte": 1 },
    "transpirable": { "deporte": 1 },
    "Inesis": { "marca": 1 },
    "WW500": { "modelo": 1 },
    "RAYA": { "marca": 1 },
    "LATERAL": { "modelo": 1 },
    "TIRO": { "modelo": 4 },
    "ESSENTIAL": { "modelo": 2 },
    "YOUTH": { "edad": 1 },
    "Power": { "marca": 3 },
    "Negro": { "color": 13 },
    "Air": { "marca": 2 },
    "Max": { "marca": 1 },
    "Sensational": { "marca": 2 },
    "Color": { "color": 1 },
    "Club": { "marca": 2, "deporte": 1 },
    "faith": { "marca": 1 },
    "push": { "modelo": 1, "tipo": 1 },
    "in": { "tamaño": 1 },
    "BALONCESTO": { "deporte": 1 },
    "sensational": { "marca": 1 },
    "Efecto": { "efecto": 2 },
    "Piel": { "género": 1, "marca": 1 },
    "Oversized": { "modelo": 1 },
    "cintura": { "cintura": 1 },
    "gomas": { "gomas": 1 },
    "Pitillo": { "categoría": 1 },
    "traje": { "traje": 2 },
    "plumas": { "plumas": 1 },
    "brillo": { "brillo": 2 },
    "PERSONALIZABLE": { "deporte": 2 },
    "flare": { "flare": 2 },
    "Feelcozy": { "marca": 1 },
    "SQ21": { "modelo": 1 },
    "high": { "alto": 4 },
    "waist": { "ancho": 4 },
    "pockets": { "ancho": 3 },
    "Storm": { "marca": 1 },
    "Outdoor": { "modelo": 1, "marca": 1 },
    "Boot": { "modelo": 1 },
    "Cut": { "tamaño": 1 },
    "All": { "modelo": 1, "tendencia": 1, "categoría": 1 },
    "Szn": { "talle": 1 },
    "Berghaus": { "marca": 1 },
    "Hike": { "marca": 1 },
    "Pirata": { "marca": 1 },
    "resinado": { "tipo": 1 },
    "Nicce": { "marca": 2 },
    "Sports": { "deporte": 1 },
    "Coated": { "coating": 3 },
    "ZURITO": { "marca": 2 },
    "CORTES": { "modelo": 1 },
    "TIRO19": { "modelo": 1 },
    "Essentials": { "modelo": 4 },
    "Regular": { "tamaño": 1 },
    "Tapered": { "tamaño": 1 },
    "POWER": { "marca": 2 },
    "acampanado": { "modelo": 2 },
    "College": { "deporte": 1 },
    "Mujer": { "género": 9 },
    "Jegging": { "categoría": 1 },
    "RECTO": { "recto": 3 },
    "Future": { "modelo": 1 },
    "Icons": { "modelo": 1 },
    "recto": { "recto": 6 },
    "tobillero": { "tobillero": 2 },
    "Ribcage": { "marca": 2 },
    "Fine": { "categoría": 1 },
    "Box": { "deporte": 1 },
    "relax": { "relajado": 1 },
    "Fit": { "tamaño": 1, "modelo": 1, "talle": 1 },
    "Smart": { "marca": 1 },
    "Flex": { "marca": 1 },
    "Alpha": { "marca": 1 },
    "piel": { "piel": 1, "marca": 1 },
    "desgastada": { "deporte": 1 },
    "Issue": { "modelo": 1 },
    "lomena": { "deporte": 1 },
    "moldeadores": { "marca": 1 },
    "Cropped": { "talle": 1 },
    "azul": { "color": 6 },
    "marino": { "color": 2 },
    "palazzo": { "palazzo": 1 },
    "denim": { "modelo": 1, "denim": 1 },
    "bicolor": { "color": 1 },
    "Alessandro": { "marca": 1 },
    "Zavetti": { "marca": 1 },
    "Mazzola": { "marca": 1 },
    "Glacier": { "modelo": 1 },
    "Oblique": { "tendencia": 1 },
    "Over": { "tendencia": 1 },
    "Print": { "tendencia": 1 },
    "Juventus": { "deporte": 1 },
    "Designed": { "modelo": 1 },
    "for": { "deporte": 1 },
    "Gameday": { "deporte": 1 },
    "antidesgarros": { "deporte": 1 },
    "Puño": { "marca": 1 },
    "Basic": { "modelo": 2 },
    "Athletic": { "categoría": 1 },
    "Marino": { "color": 4 },
    "AEROREADY": { "marca": 1 },
    "Stanford": { "deporte": 1 },
    "Open": { "deporte": 1, "modelo": 1 },
    "Hem": { "modelo": 1 },
    "Embroidered": { "modelo": 1 },
    "Small": { "tamaño": 1, "talle": 1 },
    "Camiseta": { "categoría": 1 },
    "+": { "categoría": 1 },
    "infantil": { "edad": 1 },
    "100%": { "material": 1 },
    "poliéster": { "material": 1 },
    "LOVE": { "marca": 1 },
    "Navy": { "marca": 1 },
    "Deflect": { "marca": 1 },
    "Up": { "deporte": 1, "modelo": 1 },
    "Bandeau": { "marca": 1 },
    "Bralette": { "marca": 1 },
    "tejanero": { "deporte": 1 },
    "Arch": { "modelo": 1 },
    "sastre": { "sastre": 2 },
    "Olympique": { "marca": 1 },
    "Marseille": { "modelo": 1 },
    "Embroidery": { "marca": 1 },
    "Hi-Ball": { "modelo": 1 },
    "Roll": { "modelo": 1 },
    "Swoosh": { "marca": 1 },
    "EMBROIDERY": { "marca": 1 },
    "jacquard": { "jacquard": 1 },
    "espiga": { "espiga": 1 },
    "seda": { "seda": 1 },
    "naif": { "color": 1 },
    "yoga": { "deporte": 1 },
    "embarazada": { "deporte": 1 },
    "ecofriendly": { "deporte": 1 },
    "Kimjaly": { "marca": 1 },
    "Wales": { "país": 1 },
    "SZN": { "categoría": 1 },
    "anchos": { "largo": 1 },
    "REFLECTOR": { "marca": 1 },
    "Barcelona": { "equipo": 1 },
    "Teech": { "modelo": 1 },
    "pinzas": { "pinzas": 1 },
    "navy": { "color": 1 },
    "Chelsea": { "marca": 1 },
    "Strike": { "modelo": 1 },
    "cinturilla": { "tela": 1 },
    "elástica": { "tela": 1 },
    "Oskar": { "marca": 1 },
    "Mel": { "modelo": 1 },
    "Converse": { "marca": 1 },
    "Chuck": { "marca": 1 },
    "Taylor": { "marca": 1 },
    "Metallic": { "color": 1 },
    "HIGH-WAIST": { "talle": 1 },
    "Primeblue": { "color": 1 },
    "Mom": { "género": 1 },
    "Algodón": { "material": 1 },
    "B": { "modelo": 2 },
    "desteñidos": { "desteñido": 1 },
    "CONTRASTE": { "marca": 1 },
    "Lacoste": { "marca": 2 },
    "botones": { "detalle": 1 },
    "Calvin": { "marca": 1 },
    "Klein": { "marca": 1 },
    "Modern": { "modelo": 1 },
    "Cotton": { "material": 1 },
    "DRI-FIT": { "marca": 1 },
    "BLOQUES": { "deporte": 1 },
    "Trefoil": { "marca": 1 },
    "jogging": { "deporte": 1 },
    "Core": { "marca": 1 },
    "Lounge": { "modelo": 1 },
    "Cealus": { "marca": 1 },
    "PRINT": { "marca": 1 },
    "CINTURA": { "marca": 1 },
    "Corto": { "largo": 1, "corto": 1 },
    "Ciclismo": { "deporte": 1 },
    "MTB": { "deporte": 1 },
    "Rockrider": { "marca": 1 },
    "RACE": { "modelo": 1 },
    "Suecia": { "país": 1 },
    "City": { "deporte": 1, "equipo": 1 },
    "Ampere": { "modelo": 1 },
    "Solid": { "modelo": 1 },
    "paperbag": { "papel": 1 },
    "Conjunto": { "categoría": 2 },
    "jersey": { "categoría": 1 },
    "cuello": { "categoría": 1 },
    "polo": { "categoría": 1 },
    "body": { "categoría": 1 },
    "pastel": { "marca": 1 },
    "Minnie": { "marca": 1 },
    "Mouse": { "género": 1 },
    "Set": { "categoría": 1 },
    "sudadera": { "categoría": 1 },
    "Alight": { "modelo": 1 },
    "CHANDAL": { "marca": 1 },
    "CREMALLERA": { "cremallera": 1 },
    "SUBLIMADO": { "deporte": 1 },
    "RUGBY": { "deporte": 1 },
    "2023/24": { "temporada": 1 },
    "Third": { "modelo": 1 },
    "Culotte": { "talle": 2 },
    "DRY": { "marca": 1 },
    "GET": { "marca": 1 },
    "tejido": { "tejido": 1 },
    "zig": { "zig": 1 },
    "zag": { "zag": 1 },
    "NEOFLEECE": { "marca": 1 },
    "CUFF": { "modelo": 1 },
    "Essential": { "marca": 1, "modelo": 1 },
    "SPORT": { "marca": 1 },
    "VOLEY": { "deporte": 2 },
    "SWOOSH": { "marca": 1 },
    "Linear": { "modelo": 1 },
    "Peak": { "marca": 1 },
    "Wash": { "modelo": 1 },
    "entrenamiento": { "entrenamiento": 1 },
    "Chinos": { "categoría": 1 },
    "Original": { "modelo": 1 },
    "Lab": { "modelo": 1 },
    "Lane": { "marca": 1 },
    "SLOUCHY": { "modelo": 1 },
    "raso": { "raso": 1 },
    "Graphic": { "marca": 1 },
    "Croc": { "marca": 1 },
    "Arid": { "categoría": 1 },
    "pijama": { "categoría": 1 },
    "MALLA": { "talle": 1 },
    "ajustado": { "ajustado": 1 },
    "Sarah": { "marca": 1 },
    "micro": { "micro": 1 },
    "Repeat": { "marca": 1 },
    "By": { "marca": 1 },
    "velvet": { "material": 1 },
    "PIPPING": { "marca": 1 },
    "BOLSILLOS": { "modelo": 1 },
    "EXTERNOS": { "modelo": 1 },
    "On": { "marca": 1 },
    "Running": { "deporte": 1 },
    "Active": { "deporte": 1 },
    "fitness": { "fitness": 1 },
    "algodón": { "algodón": 1 },
    "Domyos": { "marca": 1 }
  } as Record<string, Record<string, number>>
