export default {
  jean: { categoria: 85 },
  estrecho: { estrecho: 23, deporte: 1, tamano: 1, corte: 1 },
  talle: { talle: 39, largo: 9 },
  alto: {
    alto: 35,
    altura: 3,
    rendimiento: 1,
    talle: 1,
    largo: 1,
  },
  "™": { marca: 82 },
  infantil: { categoria: 5, edad: 2, talle: 2 },
  corte: { corte: 70 },
  pantalon: { categoria: 482, modelo: 1 },
  pitillo: {
    talle: 14,
    pitillo: 3,
    modelo: 11,
    corte: 4,
    tipo: 4,
    categoria: 1,
  },
  cremallera: { cremallera: 11 },
  baloncesto: { deporte: 6 },
  adulto: { edad: 17 },
  chino: {
    genero: 6,
    modelo: 11,
    color: 1,
    chino: 1,
    marca: 2,
    categoria: 2,
  },
  slim: {
    tamano: 14,
    modelo: 7,
    largo: 2,
    slim: 10,
    corte: 3,
    ancho: 1,
    tipo: 2,
    basico: 1,
    talle: 5,
    estilo: 1,
  },
  fit: {
    modelo: 8,
    tipo: 2,
    fit: 4,
    ancho: 1,
    basico: 1,
    tamano: 3,
    estilo: 2,
    talle: 1,
  },
  cuadros: {
    cuadros: 3,
    deporte: 2,
    marca: 4,
    corte: 1,
    modelo: 1,
    color: 2,
    diseno: 1,
  },
  "bi-stretch": { "bi-stretch": 1 },
  estampado: { estampado: 12, marca: 3 },
  flor: { flor: 1 },
  dorada: { color: 1 },
  nike: { marca: 117 },
  "a.p.s.": { marca: 4 },
  "therma-fit": { marca: 6 },
  versatil: { modelo: 2, tecnica: 1 },
  hombre: { genero: 127, color: 1, "genero,edad": 3 },
  vaquero: { marca: 4, vaquero: 1, categoria: 11, deporte: 2 },
  taper: { modelo: 1 },
  conico: { corte: 10, conico: 5 },
  vaqueros: {
    categoria: 70,
    deporte: 10,
    genero: 1,
    modelo: 2,
    entallados: 1,
  },
  tirantes: { tirantes: 2 },
  vila: { marca: 5 },
  skinny: { modelo: 8, talle: 5, "tipo de pantalon": 3, tipo: 2 },
  legging: { categoria: 4 },
  push: { modelo: 3, tipo: 1, deporte: 2, marca: 1 },
  up: { modelo: 3, tipo: 1, deporte: 2 },
  new: { marca: 6, modelo: 4 },
  balance: { marca: 4 },
  combat: { modelo: 2 },
  cargo: {
    modelo: 18,
    deporte: 6,
    cargo: 14,
    "tipo de pantalon": 2,
    categoria: 2,
    tela: 1,
  },
  pants: { categoria: 35 },
  jogger: { modelo: 1 },
  metalico: { material: 1 },
  plata: { color: 1 },
  doble: { tejido: 1, pinza: 1 },
  tejido: { tejido: 38, material: 2 },
  pantalones: { categoria: 111, pantalones: 1, modelo: 3 },
  chinos: {
    chinos: 1,
    modelo: 3,
    entallado: 1,
    tipo: 3,
    genero: 1,
    categoria: 1,
  },
  holgados: {
    holgados: 1,
    modelo: 4,
    tipo: 2,
    estilo: 2,
    "tipo de vaquero": 1,
    talle: 1,
    tamano: 1,
  },
  negros: { negros: 3, color: 14 },
  asos: { marca: 100 },
  design: { marca: 57, modelo: 38 },
  petite: { tamano: 4, genero: 3 },
  fred: { marca: 1 },
  perry: { marca: 1 },
  classic: { modelo: 1 },
  swim: { modelo: 1 },
  cortos: { largo: 26 },
  vestir: { vestir: 5, modelo: 1 },
  color: { color: 9 },
  piedra: { piedra: 2, color: 1, lavado: 1 },
  tapered: { tapered: 13, tamano: 1 },
  adidas: { marca: 66 },
  originals: { marca: 4 },
  adicolor: { color: 10 },
  classics: { modelo: 7 },
  adibreak: { deporte: 3 },
  superestrecho: { superestrecho: 8, tamano: 2, talle: 1 },
  adolescentes: { edad: 9, genero: 3 },
  under: { marca: 1 },
  armour: { marca: 2 },
  ua: { marca: 1 },
  fleece: {
    marca: 4,
    material: 5,
    modelo: 4,
    deporte: 3,
    tejido: 10,
    categoria: 5,
  },
  track: { modelo: 20, deporte: 2, marca: 1 },
  junior: { edad: 18, genero: 10 },
  recto: { recto: 23, talle: 2, corte: 1 },
  castore: { marca: 2 },
  wolverhampton: { deporte: 1 },
  wanderers: { deporte: 1 },
  training: { modelo: 3, deporte: 12 },
  jnr: { tamano: 1 },
  tenth: { marca: 26, deporte: 6, modelo: 7, genero: 1 },
  costura: { modelo: 1 },
  delantera: { talle: 1, tipo: 1 },
  mujer: { genero: 70 },
  joggers: { categoria: 44, modelo: 5, joggers: 1, tendencia: 1 },
  acg: { marca: 33 },
  smith: { modelo: 6, marca: 1 },
  summit: { modelo: 6 },
  air: { marca: 30, material: 1 },
  deportivo: { deporte: 5, deportivo: 15, categoria: 7 },
  "mount-strech": { modelo: 3 },
  true: { marca: 3 },
  cropped: { largo: 4, modelo: 1, talle: 1, corto: 1 },
  casual: { categoria: 19, modelo: 8, clase: 1, casual: 1 },
  texturas: { marca: 1, modelo: 1 },
  satinado: { satinado: 2 },
  terciopelo: { terciopelo: 2, traje: 1 },
  negro: { color: 67, negro: 1, modelo: 1 },
  combinables: { combinables: 2 },
  jeans: { categoria: 83, marca: 1 },
  ligero: { ligero: 3 },
  lavado: {
    lavado: 54,
    modelo: 3,
    "tipo de lavado": 1,
    tamano: 1,
    talle: 1,
  },
  kick: { modelo: 5 },
  flare: { modelo: 5, flare: 4, marca: 1 },
  sostenible: { marca: 4, sustentabilidad: 3 },
  fluido: { fluido: 5 },
  geometrico: { geometrico: 1 },
  pack: { categoria: 5 },
  tipo: { tipo: 2 },
  boxer: { deporte: 1 },
  corazones: { deporte: 1 },
  club: { modelo: 4, marca: 3, deporte: 3, categoria: 1 },
  nino: { genero: 35, edad: 16 },
  lunares: { estampado: 1 },
  lino: { material: 1 },
  culotte: { culotte: 1, talle: 2 },
  tiro: { tiro: 5, deporte: 7, modelo: 8 },
  ondas: { marca: 1 },
  futbol: { deporte: 36 },
  academy: { modelo: 2, deporte: 1, marca: 5 },
  pana: {
    pana: 6,
    marca: 5,
    deporte: 2,
    modelo: 1,
    tejido: 1,
    color: 1,
  },
  cinturon: { cinturon: 2, categoria: 1 },
  the: { marca: 7, modelo: 1, genero: 1 },
  north: { marca: 5 },
  face: { modelo: 5 },
  mountain: { deporte: 1, modelo: 1 },
  athletics: { deporte: 1, modelo: 1 },
  woven: { tela: 4, "tipo de pantalon": 6, tejido: 5, material: 1 },
  bolsillos: {
    bolsillos: 11,
    largo: 1,
    bolsillo: 1,
    deporte: 3,
    modelo: 1,
  },
  wide: { larga: 2, ancho: 1, largo: 2 },
  leg: { largo: 3, talle: 1 },
  full: { largo: 2 },
  length: { largo: 2 },
  regular: { tipo: 2, regular: 8, tamano: 2, modelo: 2 },
  campana: { campana: 4, marca: 1 },
  canale: { color: 1, cremallera: 1 },
  bajos: {
    bajos: 5,
    categoria: 1,
    talle: 2,
    largo: 1,
    modelo: 1,
  },
  ondulados: { ondulados: 1 },
  winter: { deporte: 1 },
  warrior: { modelo: 1 },
  "levi's": { marca: 12 },
  baggy: { modelo: 1 },
  tall: { talle: 9, tamano: 1 },
  punto: { punto: 5, marca: 3, deporte: 2, modelo: 2 },
  beige: { color: 6 },
  rectos: { rectos: 2 },
  wedgie: { marca: 2 },
  conjunto: { categoria: 63, modelo: 1 },
  jersey: { categoria: 27 },
  spf: { marca: 56 },
  termico: { termico: 14 },
  interior: { interior: 16 },
  lana: { lana: 3, color: 1 },
  merina: { deporte: 2 },
  esqui: { deporte: 23 },
  nieve: { deporte: 18 },
  wedze: { marca: 10 },
  bl900: { modelo: 1 },
  chandal: {
    chandal: 18,
    marca: 18,
    deporte: 6,
    categoria: 3,
    modelo: 1,
  },
  cordon: { cordon: 18 },
  ajuste: { ajuste: 10 },
  feelcozy: { marca: 2 },
  desgastado: { desgastado: 8 },
  rasgados: { rasgados: 1 },
  marcados: { marca: 1 },
  jeggings: { categoria: 1 },
  caza: { categoria: 2, deporte: 6 },
  solognac: { marca: 7 },
  softshell: { material: 1 },
  silencioso: { material: 1, calidad: 1 },
  camuflaje: {
    material: 1,
    color: 1,
    marca: 1,
    calidad: 1,
    modelo: 1,
  },
  sigilo: { material: 1 },
  equitacion: { equipamiento: 1, deporte: 2, competicion: 1 },
  fouganza: { marca: 4 },
  blanco: { color: 10 },
  badanas: { marca: 1 },
  adherentes: { marca: 1 },
  concurso: { deporte: 1 },
  evoked: { marca: 1 },
  by: { marca: 2 },
  tallas: { tamano: 3 },
  corto: { largo: 54, corto: 2 },
  short: { modelo: 2, largo: 2 },
  own: { marca: 1 },
  run: { deporte: 1 },
  puma: { marca: 23 },
  ess: { marca: 4, modelo: 1 },
  ned: { modelo: 1 },
  gray: { color: 1 },
  heather: { color: 1 },
  gris: { color: 21 },
  ancho: { ancho: 7 },
  militar: { deporte: 1 },
  "wed'ze": { marca: 1 },
  technicals: { categoria: 1 },
  volta: { deporte: 1 },
  supply: { marca: 4 },
  demand: { marca: 4 },
  indi: { categoria: 1 },
  lady: { marca: 1 },
  loop: { marca: 1 },
  azul: { color: 47 },
  ombre: { color: 1 },
  rugby: { deporte: 8 },
  personalizado: {
    deporte: 6,
    personalizacion: 2,
    modelo: 1,
    edad: 1,
  },
  cm: { longitud: 6 },
  oscuro: { oscuro: 4, color: 5 },
  camisa: { categoria: 10 },
  sudadera: { categoria: 8, sudadera: 1 },
  camel: { genero: 1, color: 2, modelo: 1 },
  rayas: { color: 2, rayas: 2 },
  marine: { color: 3, modelo: 1 },
  cinturilla: { cinturilla: 2, tipo: 1, tela: 1, talle: 1 },
  angeles: { deporte: 1, ciudad: 1 },
  lakers: { deporte: 1, equipo: 1 },
  nba: { deporte: 9, marca: 1 },
  pijama: { modelo: 6, pijama: 3, categoria: 1 },
  mom: { genero: 12 },
  origin: { origen: 2, pais: 1, marca: 2, deporte: 1 },
  padelpersonalizable: { marca: 2 },
  elasticos: { material: 6, entallados: 1, elasticos: 2 },
  ensuciado: { "tipo de lavado": 1, ensuciado: 2 },
  resistentes: { resistencia: 1 },
  agua: { deporte: 1, agua: 1 },
  caqui: { color: 2 },
  acolchados: { "tipo de pantalon": 1 },
  raya: { raya: 5, marca: 1 },
  diplomatica: { modelo: 1, marca: 1, diplomatica: 1 },
  strass: { marca: 1 },
  rita: { modelo: 1, marca: 2 },
  ora: { genero: 3 },
  fr900: { marca: 2 },
  reebok: { marca: 3 },
  ninos: { genero: 11, edad: 2 },
  cenido: {
    corte: 3,
    conico: 2,
    cuello: 2,
    canon: 13,
    moldeador: 2,
    cintura: 1,
  },
  ajustados: {
    ajustados: 17,
    categoria: 1,
    modelo: 5,
    ajuste: 3,
    ajustado: 1,
    largo: 1,
  },
  tobillo: { talle: 1 },
  limpio: { color: 2, modelo: 1 },
  lisbon: { marca: 2 },
  encerado: { tipo: 1, encerado: 1, efecto: 1 },
  sastre: { talle: 1, sastre: 3 },
  pliegues: { detalle: 1 },
  delanteros: { detalle: 1 },
  detalle: { detalle: 4 },
  trabilla: { detalle: 1 },
  boton: { detalle: 1 },
  logotipo: { marca: 2 },
  cobra: { marca: 1 },
  kai: { marca: 1 },
  botines: { categoria: 1 },
  verde: { color: 10 },
  kaki: { color: 8 },
  sarga: { sarga: 2, deporte: 1 },
  efecto: { efecto: 12 },
  personalizable: { personalizacion: 2, deporte: 2 },
  mckenzie: { marca: 4 },
  moran: { marca: 1 },
  poly: { material: 2 },
  calidos: { calidad: 1 },
  revestimiento: { revestimiento: 1 },
  fondo: { deporte: 7 },
  inovik: { marca: 6 },
  xc: { modelo: 5, marca: 1 },
  s: { tamano: 4, marca: 1 },
  evostripe: { marca: 1 },
  lurex: { lurex: 1 },
  dorado: { dorado: 1 },
  mile: { modelo: 4 },
  high: { marca: 4, alto: 4 },
  hoodrich: { marca: 6 },
  area: { categoria: 2 },
  traje: { traje: 11, deporte: 1, modelo: 3 },
  premium: { marca: 2, premium: 1, categoria: 1 },
  curve: { modelo: 2 },
  angel: { marca: 1 },
  disney: { marca: 9 },
  logo: { marca: 9 },
  nina: { genero: 7, edad: 1 },
  senderismo: { deporte: 2 },
  manchester: { deporte: 2, ciudad: 2 },
  united: { deporte: 3 },
  dna: { marca: 2 },
  bandas: { marca: 1, material: 1, tela: 1, modelo: 1 },
  cremalleras: { deporte: 1 },
  parka: { categoria: 4 },
  camiseta: { categoria: 8, modelo: 3 },
  retro: { retro: 1 },
  diseno: { diseno: 6, marca: 1 },
  elastico: { elastico: 5, material: 3, entallado: 4 },
  jordan: { marca: 10 },
  x: { categoria: 1, marca: 1 },
  titan: { modelo: 1 },
  acampanado: { deporte: 1, modelo: 2 },
  abrigo: { categoria: 1 },
  light: { tamano: 1, modelo: 1 },
  spray: { marca: 2 },
  on: { modelo: 2, marca: 1 },
  set: { categoria: 2 },
  bralette: { bralette: 1, marca: 1 },
  barbie: { marca: 1 },
  movie: { deporte: 1 },
  super: { categoria: 1 },
  "storm-fit": { modelo: 1, marca: 1 },
  rope: { modelo: 1 },
  dope: { deporte: 1 },
  grises: { color: 2 },
  pernera: {
    talle: 5,
    pernera: 1,
    material: 1,
    ancha: 1,
    tela: 1,
  },
  ancha: { talle: 1, largo: 2, ancha: 2 },
  anilla: { talle: 1, anilla: 1 },
  d: { modelo: 1 },
  clasicos: { modelo: 2, clasicos: 8 },
  champion: { marca: 2 },
  legacy: { marca: 1, modelo: 1 },
  american: { marca: 1 },
  tape: { marca: 3, tape: 1 },
  entallado: { entallado: 6 },
  estampados: { estampado: 1, estampados: 1 },
  bocetos: { bocetos: 1 },
  daisy: { marca: 2 },
  nautica: { marca: 1 },
  kea: { modelo: 1 },
  cintura: { cintura: 3, categoria: 1, marca: 1 },
  elastica: { elastica: 1, material: 2, tela: 2, talle: 1 },
  rigido: { rigido: 1, modelo: 1 },
  look: { modelo: 4 },
  newcastle: { deporte: 1 },
  fc: { deporte: 4, equipo: 2 },
  travel: { modelo: 2 },
  denim: { talle: 1, modelo: 1, denim: 1, color: 1 },
  tarmak: { marca: 1 },
  sh900: { modelo: 1 },
  adv: { marca: 4 },
  golf: { deporte: 3 },
  sport: { deportes: 1, marca: 1 },
  comfort: { modelo: 2, marca: 1 },
  knit: { modelo: 1, tejido: 7 },
  cenidos: { cadenas: 3 },
  polartec: { marca: 5 },
  "®": { marca: 25 },
  wolf: { marca: 5, modelo: 2 },
  tree: { modelo: 4, marca: 3 },
  estructura: { estructura: 1 },
  capucha: { capucha: 1, categoria: 1 },
  lazo: { corte: 1 },
  voleibol: { deporte: 1 },
  allsix: { marca: 1 },
  v100: { modelo: 1 },
  bootcut: { modelo: 4, marca: 1 },
  chaqueta: { modelo: 1, categoria: 1 },
  rotos: { modelo: 2 },
  dad: { genero: 1 },
  vintage: { modelo: 2 },
  roturas: { modelo: 1, roturas: 2 },
  paris: { departamento: 1 },
  saint: { departamento: 1 },
  germain: { departamento: 1 },
  boston: { marca: 6 },
  celtics: { equipo: 4, deporte: 2 },
  icon: { modelo: 2, marca: 2 },
  edition: { modelo: 5 },
  swingman: { deporte: 1, modelo: 4 },
  sst: { modelo: 1, marca: 3 },
  basico: { basico: 4, modelo: 2 },
  juego: { deporte: 2 },
  paracaidista: { deporte: 2 },
  "3s": { marca: 1, deporte: 1, modelo: 1, tamano: 1, talle: 1 },
  fl: { marca: 1 },
  tc: { marca: 1 },
  pt: { marca: 1, modelo: 1 },
  algodon: { deporte: 2, marca: 2, material: 4, algodon: 2 },
  cazadora: { categoria: 2 },
  bota: { categoria: 3 },
  anil: { color: 1, tipo: 1 },
  entallados: { entallado: 2, entallados: 1 },
  estandar: { estilo: 1, entallados: 1 },
  trail: { deporte: 3, marca: 1 },
  transformable: { deporte: 1, transformable: 2 },
  talla: { tamano: 3, talle: 2 },
  azules: { color: 2 },
  mblue: { marca: 2 },
  atlanta: { marca: 1 },
  hawks: { deporte: 1 },
  "2023/24": { temporada: 3 },
  city: { modelo: 4, deporte: 1, equipo: 1, marca: 1 },
  "dri-fit": { marca: 25, tecnica: 1, material: 1 },
  engomado: { engomado: 1 },
  tencel: { marca: 1 },
  lyocell: { marca: 1 },
  volante: { modelo: 1 },
  bliss: { marca: 2 },
  malla: { malla: 3, talle: 1 },
  forno: { marca: 1 },
  impermeable: { marca: 2, impermeable: 2, material: 4 },
  miles: { nombre: 1 },
  morales: { nombre: 1 },
  "spider-man": { nombre: 1, deporte: 2 },
  marvel: { marca: 3 },
  ultimate: { marca: 4 },
  inglaterra: { pais: 5 },
  strike: { marca: 5, modelo: 4 },
  metalizadas: { material: 1 },
  pinzas: { deporte: 2, pinzas: 3 },
  asics: { marca: 1 },
  s500: { tamano: 1 },
  vientre: { tipo: 1, deporte: 1 },
  maternity: { genero: 3, modelo: 1 },
  calido: { calor: 2, temperatura: 1, calidad: 1, modelo: 1 },
  pirata: { marca: 2 },
  montirex: { marca: 2 },
  fly: { marca: 2 },
  "2.0": { modelo: 1 },
  "ski-p": { modelo: 3 },
  pa500: { modelo: 1 },
  "ess+tape": { marca: 1 },
  sweatpants: { modelo: 2 },
  identity: { marca: 1 },
  french: { marca: 4 },
  terry: { marca: 4 },
  presentacion: { presentacion: 1 },
  japan: { pais: 1 },
  "6-14": { edad: 2 },
  anos: { edad: 1, anos: 2, deporte: 1, modelo: 1 },
  uw: { marca: 2, tamano: 1 },
  rigidos: { rigidos: 7, tipo: 1 },
  mezcla: { mezcla: 2 },
  sobrecamisa: { categoria: 8 },
  moldeador: { marca: 2, modelo: 3, moldeador: 3 },
  padel: { deporte: 13 },
  modelo: { marca: 1, modelo: 1 },
  cup: { marca: 2 },
  fitness: { fitness: 3, deporte: 4 },
  cardio: { cardio: 1 },
  sereno: { modelo: 5, marca: 2 },
  beckenbauer: { deporte: 3 },
  jaspeados: { material: 1, modelo: 1 },
  rendimiento: { rendimiento: 1 },
  seam: { marca: 1 },
  cadera: { categoria: 1 },
  cuero: { categoria: 1 },
  hebilla: { categoria: 1 },
  plateada: { marca: 1 },
  leggins: { categoria: 1 },
  costuras: { costuras: 1 },
  kipsta: { marca: 2 },
  viralto: { modelo: 1, marca: 1 },
  fluor: { color: 1 },
  marismas: { color: 1 },
  juicy: { marca: 1 },
  couture: { marca: 1 },
  diamante: { marca: 1 },
  velour: { marca: 2 },
  recta: { recta: 1, tamano: 1, tela: 1 },
  lentejuelas: { lentejuelas: 1 },
  superpitillo: { "tipo de corte": 1, "tipo de pantalon": 1 },
  rodillas: { "tipo de rodillas": 1, tamano: 1 },
  rasgadas: { "tipo de rasgadas": 1, tamano: 1 },
  piel: { piel: 3, genero: 1, marca: 2 },
  borrego: { color: 1 },
  sintetica: { material: 1 },
  original: { modelo: 10 },
  atletico: { marca: 5, deporte: 2 },
  madrid: { deporte: 4, marca: 1, ciudad: 2 },
  standard: { modelo: 4 },
  issue: { modelo: 2, categoria: 1 },
  cr: { equipo: 1 },
  flamengo: { equipo: 1 },
  teamgeist: { modelo: 1 },
  steppe: { marca: 1 },
  resistente: { resistencia: 2, resistente: 1 },
  multibolsillos: { material: 1 },
  icono: { marca: 1 },
  vengadores: { deporte: 1 },
  aeroswift: { marca: 2 },
  running: { deporte: 4 },
  duffer: { marca: 1 },
  of: { marca: 1 },
  st: { modelo: 2 },
  george: { modelo: 1 },
  jogging: { modelo: 1, deporte: 1 },
  children: { edad: 1 },
  flex: { flexibilidad: 1, marca: 1, categoria: 1 },
  sobrepantalon: { categoria: 3 },
  bicicleta: { modelo: 1 },
  ciudad: { deporte: 1 },
  cubrecalzado: { deporte: 1 },
  integrado: { deporte: 1 },
  techfleece: { marca: 1 },
  bicolor: { color: 3 },
  tintado: { tintado: 3 },
  exclusivo: { modelo: 1 },
  decimas: { modelo: 1 },
  essentials: { modelo: 5 },
  colorblock: { modelo: 1, marca: 1 },
  cardigan: { categoria: 2 },
  paperbag: { modelo: 1, papel: 1 },
  minnie: { marca: 2 },
  mouse: { genero: 2, marca: 1 },
  solognac100: { marca: 1 },
  monocromaticos: { color: 1 },
  sands: { talle: 1, modelo: 2 },
  tommy: { marca: 2 },
  "3-pack": { modelo: 1 },
  lace: { tela: 1 },
  thongs: { tela: 1 },
  con20: { modelo: 1 },
  tachas: { tachas: 1 },
  antracita: { color: 4 },
  chaleco: { categoria: 1 },
  ninas: { genero: 1 },
  tobillero: { tobillero: 3 },
  estilo: { estilo: 4 },
  monocolor: { modelo: 1 },
  anchos: { anchos: 1, largo: 1 },
  yoga: { deporte: 3, marca: 1 },
  byrant: { modelo: 1 },
  pelillo: { corte: 1 },
  texturizado: { corte: 1 },
  grafico: { grafico: 3 },
  unstopabble: { marca: 2 },
  holgado: { largo: 1 },
  tie: { marca: 1 },
  dye: { marca: 1 },
  hourglass: { edad: 1, marca: 1 },
  straight: { estilo: 2, straight: 1 },
  pato: { marca: 1 },
  donald: { marca: 1 },
  mercier: { marca: 1 },
  kansas: { modelo: 1 },
  york: { marca: 1 },
  knicks: { marca: 1 },
  embarazada: { marca: 1, genero: 1, deporte: 1 },
  ecofriendly: { marca: 2, deporte: 1 },
  zapato: { categoria: 1 },
  b: { modelo: 3 },
  shorts: { modelo: 1, categoria: 1 },
  transpirable: { deporte: 3 },
  inesis: { marca: 1 },
  ww500: { modelo: 1, marca: 1 },
  lateral: { modelo: 1, lateral: 3, largo: 1, longitud: 1 },
  falda: { categoria: 3 },
  essential: { modelo: 3, marca: 1 },
  youth: { edad: 1 },
  power: { marca: 5 },
  max: { marca: 2 },
  blusa: { categoria: 2 },
  ajustado: { ajustado: 2 },
  domyos: { marca: 2 },
  "+": { modelo: 1, categoria: 1 },
  sensational: { marca: 3 },
  deportivos: { deportivo: 1, deporte: 1 },
  faith: { marca: 1 },
  in: { tamano: 1 },
  blazer: { categoria: 1 },
  swix: { marca: 2 },
  race: { modelo: 4 },
  trekking: { trekking: 2 },
  desierto: { deporte: 1 },
  upf40: { marca: 1 },
  forclaz: { marca: 1 },
  desert: { modelo: 1 },
  marron: { color: 2 },
  claros: { color: 1 },
  pinza: { pinza: 1 },
  snow: { deporte: 1 },
  unisex: { genero: 1 },
  escalada: { deporte: 1 },
  simond: { marca: 2 },
  oversized: { modelo: 1 },
  gomas: { gomas: 1 },
  snowgrass: { modelo: 1 },
  bullpadel: { marca: 1 },
  llano: { modelo: 1 },
  popelina: { marca: 1 },
  plumas: { plumas: 1 },
  raso: { raso: 2 },
  winnie: { marca: 1 },
  pooh: { deporte: 1 },
  brillo: { brillo: 2 },
  ski580: { modelo: 2 },
  calvin: { marca: 2 },
  klein: { marca: 2 },
  leopardo: { marca: 1 },
  girls: { genero: 1 },
  tech: { marca: 1 },
  sq21: { modelo: 1 },
  bomber: { categoria: 1 },
  elegantes: { elegantes: 2 },
  principe: { marca: 1 },
  gales: { pais: 1 },
  pequeno: { edad: 2 },
  waist: { ancho: 4 },
  pockets: { ancho: 3 },
  "ski-p500": { modelo: 1 },
  storm: { marca: 1 },
  outdoor: { modelo: 1, marca: 1 },
  basicos: { basicos: 1 },
  nudo: { nudo: 1 },
  boot: { modelo: 1 },
  cut: { tamano: 1 },
  all: { modelo: 1, tendencia: 1, categoria: 1 },
  szn: { talle: 1, categoria: 1 },
  berghaus: { marca: 1 },
  hike: { marca: 1, modelo: 1 },
  ciclismo: { deporte: 3, ciclismo: 1 },
  urbano: { deporte: 1 },
  btwin: { marca: 1 },
  resinado: { tipo: 1 },
  nicce: { marca: 2 },
  sports: { deporte: 1 },
  ski: { modelo: 1 },
  competicion: { deporte: 2 },
  deportivas: { categoria: 1 },
  coated: { coating: 3 },
  zurito: { marca: 2, genero: 1 },
  cortes: { modelo: 1 },
  tiro19: { modelo: 1 },
  envejecido: { edad: 1 },
  college: { deporte: 1 },
  botones: { botones: 2, detalle: 1 },
  joya: { marca: 1 },
  jegging: { categoria: 1 },
  future: { modelo: 1 },
  icons: { modelo: 1 },
  marino: { color: 12 },
  ribcage: { marca: 2 },
  fine: { categoria: 1 },
  box: { deporte: 1 },
  relax: { relajado: 1, relaja: 2 },
  organico: { material: 2 },
  "essentials+": { modelo: 1 },
  col: { color: 1 },
  tenido: { tenido: 1 },
  smart: { marca: 1 },
  alpha: { marca: 1 },
  desgastada: { deporte: 1 },
  banda: { banda: 3 },
  lomena: { deporte: 1 },
  repelentes: { repelentes: 1 },
  action: { modelo: 1 },
  moldeadores: { marca: 1 },
  bl: { modelo: 2 },
  seamless: { tecnica: 1 },
  palazzo: { palazzo: 1 },
  hugo: { marca: 1 },
  cinder: { modelo: 1 },
  cone: { modelo: 1 },
  cortavientos: { largo: 1 },
  recortado: { recortado: 2 },
  squadra: { marca: 2 },
  supercenidos: { marca: 1 },
  beis: { deporte: 1 },
  alessandro: { marca: 1 },
  zavetti: { marca: 1 },
  mazzola: { marca: 1 },
  marcus: { nombre: 1 },
  rashford: { nombre: 1 },
  mtb: { ciclismo: 1, deporte: 1 },
  rockrider: { marca: 2 },
  glacier: { modelo: 1 },
  oblique: { tendencia: 1 },
  over: { tendencia: 1 },
  print: { tendencia: 1, marca: 1 },
  sgtr: { marca: 1 },
  reforzado: { marca: 1 },
  tiempo: { tiempo: 1 },
  seco: { estado: 1 },
  juventus: { deporte: 1 },
  designed: { modelo: 2 },
  for: { deporte: 1 },
  gameday: { deporte: 2 },
  zapatilla: { categoria: 2 },
  antidesgarros: { deporte: 1 },
  balonmano: { deporte: 1 },
  antirrozaduras: { antirrozaduras: 1 },
  puno: { marca: 1 },
  basic: { modelo: 2 },
  plus: { modelo: 1 },
  athletic: { categoria: 1, modelo: 1 },
  camieta: { categoria: 1 },
  aeroready: { marca: 1 },
  stanford: { deporte: 1 },
  open: { deporte: 1, modelo: 1 },
  hem: { modelo: 1 },
  embroidered: { modelo: 1 },
  small: { tamano: 1, talle: 1 },
  gorra: { categoria: 1 },
  panel: { panel: 1 },
  otomano: { deporte: 1 },
  "100%": { material: 1 },
  poliester: { material: 1 },
  love: { marca: 1 },
  navy: { marca: 1, color: 1 },
  deflect: { marca: 1 },
  hielo: { "tipo de hielo": 1, hielo: 1 },
  microtexturizado: { "tipo de tejido": 1, material: 1 },
  wedding: { modelo: 3 },
  bandeau: { marca: 1 },
  tejanero: { deporte: 1 },
  arch: { modelo: 1 },
  entrenamiento: { entrenamiento: 3, deporte: 2 },
  utilitario: { modelo: 1 },
  olympique: { marca: 1 },
  marseille: { modelo: 1 },
  embroidery: { marca: 2 },
  panantalon: { categoria: 1 },
  alemania: { pais: 1 },
  jacquard: { jacquard: 2 },
  "hi-ball": { modelo: 1 },
  roll: { modelo: 1 },
  swoosh: { marca: 2 },
  capri: { talle: 1 },
  effortless: { marca: 1 },
  wordmark: { marca: 6 },
  espiga: { espiga: 1 },
  seda: { seda: 1 },
  naif: { color: 1 },
  acampanados: { acampanados: 1 },
  kimjaly: { marca: 1 },
  warm: { calor: 1 },
  australia: { marca: 1 },
  wales: { pais: 1 },
  celtic: { deporte: 1 },
  reflector: { marca: 1 },
  abertura: { tipo: 1 },
  barcelona: { equipo: 1, marca: 1 },
  teech: { modelo: 1 },
  premama: { deporte: 1 },
  chelsea: { marca: 1 },
  oskar: { marca: 1 },
  mel: { modelo: 1 },
  converse: { marca: 1 },
  chuck: { marca: 1 },
  taylor: { marca: 1 },
  metallic: { color: 1 },
  "high-waist": { talle: 1 },
  primeblue: { color: 1 },
  paneles: { paneles: 1, panel: 1 },
  cosidos: { cosidos: 1 },
  "12,5": { tamano: 1 },
  oz: { tamano: 1, peso: 1 },
  autentico: { modelo: 1 },
  destenidos: { destenido: 1 },
  termicos: { termicos: 1 },
  ikar: { marca: 1 },
  lima: { deporte: 1 },
  golpe: { deporte: 1 },
  realzador: { efecto: 1 },
  voley: { deporte: 3 },
  contraste: { marca: 1 },
  lacoste: { marca: 2 },
  finas: { finas: 1 },
  white: { color: 1 },
  "7-15": { edad: 1 },
  pa: { marca: 1 },
  modern: { modelo: 1 },
  cotton: { material: 1 },
  bloques: { deporte: 1 },
  attack: { marca: 1 },
  forro: { marca: 1 },
  printed: { marca: 1 },
  trefoil: { marca: 1 },
  core: { marca: 1 },
  lounge: { modelo: 1 },
  posiciones: { posiciones: 1 },
  cealus: { marca: 1 },
  tacto: { tacto: 1 },
  suave: { suave: 1 },
  drapeado: { drapeado: 1 },
  laterales: { laterales: 1 },
  suecia: { pais: 1 },
  farleigh: { marca: 2 },
  flores: { flores: 1 },
  showtime: { modelo: 2 },
  secado: { secado: 1 },
  rapido: { rapido: 1 },
  sirsaca: { modelo: 1 },
  badminton: { deporte: 1 },
  perfly: { marca: 1 },
  m: { modelo: 1 },
  ampere: { modelo: 1 },
  solid: { modelo: 1 },
  polar: { calidad: 1, modelo: 1 },
  bosque: { deporte: 1 },
  arrugado: { efecto: 1 },
  trangoworld: { marca: 2 },
  altai: { modelo: 1 },
  th: { talle: 1 },
  cuello: { categoria: 1 },
  polo: { categoria: 1 },
  big: { tamano: 1 },
  kids: { edad: 1 },
  body: { categoria: 1 },
  pastel: { marca: 1 },
  alight: { modelo: 1 },
  pubjug: { categoria: 1 },
  sublimado: { deporte: 1 },
  verdoso: { color: 1 },
  mariposa: { color: 1 },
  acido: { deporte: 1 },
  "12.5": { tamano: 1 },
  third: { modelo: 1 },
  dry: { marca: 1 },
  get: { marca: 1 },
  zig: { zig: 1 },
  zag: { zag: 1 },
  neofleece: { marca: 1 },
  cuff: { modelo: 1 },
  personalizada: { modelo: 1 },
  canyon: { modelo: 1 },
  farer: { modelo: 1 },
  halftone: { modelo: 1 },
  k: { modelo: 1 },
  pata: { diseno: 1 },
  gallo: { diseno: 1 },
  colores: { colores: 1 },
  intenso: { intenso: 1 },
  kem: { marca: 2 },
  linear: { modelo: 1 },
  pesca: { deporte: 1 },
  submarina: { deporte: 1 },
  neopreno: { material: 1 },
  mm: { longitud: 1 },
  peak: { marca: 1 },
  wash: { modelo: 1 },
  sailing: { deporte: 1 },
  lluvia: { color: 1 },
  acabado: { acabado: 1 },
  serpiente: { marca: 1 },
  lab: { modelo: 1 },
  lane: { marca: 1 },
  tecnico: { tecnico: 1 },
  slouchy: { modelo: 1 },
  basquiat: { marca: 1 },
  patalones: { categoria: 1 },
  john: { marca: 1 },
  cital: { marca: 1 },
  conica: { talle: 1 },
  repel: { marca: 2 },
  convertible: { modelo: 1 },
  frontales: { frontales: 1 },
  edit: { marca: 1 },
  guantes: { categoria: 1 },
  gorro: { categoria: 1 },
  graphic: { marca: 1 },
  croc: { marca: 1 },
  arid: { categoria: 1 },
  encaje: { encaje: 1 },
  poliuretano: { material: 1 },
  mickey: { marca: 1 },
  clasico: { modelo: 1 },
  sarah: { marca: 1 },
  micro: { micro: 1 },
  ready: { modelo: 1 },
  montana: { montana: 1, deporte: 1 },
  ladovy: { modelo: 1 },
  repeat: { marca: 1 },
  shaping: { modelo: 1 },
  alpinismo: { deporte: 1 },
  alpinism: { modelo: 1 },
  evo: { modelo: 1 },
  muslo: { talle: 1 },
  f540: { modelo: 1 },
  velvet: { material: 1 },
  tobilleros: { tobilleros: 1 },
  anudada: { anudada: 1 },
  one: { modelo: 1 },
  pipping: { marca: 1 },
  externos: { modelo: 1 },
  active: { deporte: 1 },
} as Record<string, Record<string, number>>
