import type { LabelMap } from "./types.js"

export const schemas = {
  "jeans cropped marine": { género: 3, modelo: 2 },
  "jeans high waist pockets": { modelo: 2 },
  "jeans high": { talle: 2, pockets: 2, color: 2 },
  jeans: { waist: 2, tamaño: 2, pockets: 2, modelo: 2 },
  "jeans flare": { género: 2 },
  "pantalon denim": { ancho: 2, bicolor: 2 },
  "pantalon punto": { modelo: 2 },
} as LabelMap

export const vocabulary = {
  jeans: { categoría: 81, talle: 2, modelo: 2 },
  cropped: { categoría: 6, modelo: 1 },
  marine: { categoría: 3, marca: 1 },
  azul: {
    "género,edad": 5,
    modelo: 7,
    marca: 13,
    categoría: 10,
    marino: 1,
    azul: 1,
    deporte: 2,
    tamaño: 5,
    tonalidad: 1,
    tono: 1,
    color: 1,
  },
  negro: {
    "género,edad": 1,
    modelo: 26,
    categoría: 5,
    marca: 6,
    tamaño: 18,
    talle: 2,
    negro: 1,
    edad: 6,
    deporte: 3,
    tono: 1,
  },
  camel: { modelo: 4 },
  high: { categoría: 3, waist: 1, modelo: 4 },
  waist: { categoría: 2, largo: 1, tamaño: 1 },
  pockets: { categoría: 1, pockets: 2 },
  oscuro: { modelo: 4, categoría: 4, tamaño: 1 },
  flare: { categoría: 4, flare: 1, modelo: 5 },
  verde: {
    categoría: 5,
    género: 1,
    "género,edad": 2,
    marca: 1,
    modelo: 1,
  },
  kaki: { categoría: 3, género: 1, modelo: 3, marca: 1 },
  pantalon: { categoría: 464, modelo: 12, tamaño: 4, talle: 3 },
  denim: { categoría: 1, modelo: 2, deporte: 1 },
  ancho: { ancho: 2, categoría: 4, modelo: 1 },
  bicolor: { bicolor: 1, tono: 1, tela: 1 },
  punto: { categoría: 5, marca: 1, modelo: 5, tamaño: 1 },
  beige: { modelo: 6 },
  seda: { categoría: 1 },
  naif: { categoría: 1 },
  marino: {
    marca: 3,
    "género,edad": 1,
    marino: 1,
    categoría: 1,
    deporte: 1,
    tamaño: 3,
    tono: 1,
    color: 1,
  },
  fluido: { categoría: 5 },
  bolsillos: {
    bolsillos: 9,
    modelo: 2,
    categoría: 3,
    marca: 2,
    deporte: 1,
  },
  basico: { categoría: 5, modelo: 1 },
  cordon: { categoría: 10, modelo: 8 },
  traje: { categoría: 13, modelo: 2 },
  sastre: { categoría: 3, talle: 1 },
  pana: { categoría: 14, modelo: 1, talle: 1 },
  estampado: { categoría: 6, modelo: 2, estampado: 7 },
  geometrico: { modelo: 1 },
  flor: { categoría: 1 },
  dorada: { categoría: 1 },
  cargo: { categoría: 23, modelo: 16, tamaño: 4 },
  ondas: { modelo: 1 },
  plumas: { categoría: 1 },
  gris: {
    "género,edad": 1,
    tono: 1,
    categoría: 5,
    modelo: 2,
    tamaño: 10,
    deporte: 1,
    edad: 1,
  },
  antracita: { marca: 2, tono: 1, modelo: 1 },
  raso: { categoría: 2 },
  cintura: { categoría: 4, tamaño: 1 },
  gomas: { categoría: 1 },
  tachas: { categoría: 1 },
  lurex: { categoría: 1 },
  dorado: { modelo: 1 },
  brillo: { categoría: 1, efecto: 1 },
  jacquard: { categoría: 2 },
  espiga: { categoría: 1 },
  jogger: { categoría: 1 },
  metalico: { modelo: 1 },
  plata: { modelo: 1 },
  terciopelo: { categoría: 3 },
  cinturon: { categoría: 2, modelo: 1 },
  pinzas: { categoría: 2, pinzas: 2, "pinzas frontales": 1 },
  palazzo: { categoría: 1 },
  engomado: { engomado: 1 },
  full: { full: 1, largo: 1 },
  length: { largo: 2 },
  tencel: { marca: 1 },
  "™": { modelo: 4, marca: 78, taper: 1 },
  lyocell: { tela: 1 },
  vaquero: { marca: 9, categoría: 7, tamaño: 1, modelo: 1 },
  skinny: { modelo: 7, categoría: 8, talle: 1, tamaño: 2 },
  bandas: { modelo: 4 },
  metalizadas: { modelo: 1 },
  cuadros: { modelo: 9, categoría: 3, tamaño: 1, cuadros: 1 },
  slim: {
    categoría: 25,
    modelo: 12,
    bolsillos: 2,
    tamaño: 3,
    slim: 1,
    talle: 2,
    deporte: 1,
  },
  fit: {
    categoría: 9,
    modelo: 9,
    bolsillos: 1,
    tapered: 2,
    deporte: 1,
  },
  estructura: { modelo: 1 },
  chino: { categoría: 21, tamaño: 2 },
  push: { modelo: 4, categoría: 3 },
  up: { modelo: 3, categoría: 3 },
  vila: { categoría: 2, marca: 2, modelo: 1 },
  chinos: { categoría: 9, tamaño: 1 },
  original: { modelo: 10 },
  legging: { categoría: 4 },
  botones: { modelo: 3 },
  joya: { marca: 1 },
  recto: {
    categoría: 7,
    talle: 10,
    recto: 1,
    modelo: 7,
    tamaño: 1,
  },
  resinado: { categoría: 1 },
  vaqueros: { categoría: 78, talle: 3, modelo: 3 },
  faith: { marca: 1 },
  in: { modelo: 1 },
  acampanado: { modelo: 3 },
  tipo: { categoría: 1, modelo: 1 },
  pitillo: {
    talle: 21,
    categoría: 6,
    modelo: 9,
    "efecto realzador": 1,
  },
  holgado: { tamaño: 1 },
  talla: { tamaño: 5 },
  "bi-stretch": { categoría: 1 },
  sensational: { modelo: 1, categoría: 2 },
  evoked: { modelo: 1 },
  by: { marca: 1, modelo: 1 },
  wide: { categoría: 2, modelo: 1, largo: 1, tamaño: 1 },
  leg: { categoría: 1, modelo: 1, largo: 1, tamaño: 1 },
  encerado: { modelo: 1, categoría: 2 },
  velvet: { modelo: 1 },
  efecto: { efecto: 8, categoría: 3, modelo: 1 },
  volante: { modelo: 1 },
  cinturilla: { categoría: 4, modelo: 1 },
  elastica: { categoría: 6 },
  piel: { deporte: 1, categoría: 4, efecto: 1 },
  pantalones: { categoría: 109, modelo: 6 },
  paperbag: { categoría: 1, modelo: 1 },
  algodon: {
    marca: 3,
    categoría: 3,
    tamaño: 1,
    deporte: 1,
    género: 1,
    modelo: 1,
  },
  organico: { modelo: 1, género: 1 },
  premium: { categoría: 2, marca: 1, modelo: 1 },
  flex: { categoría: 2, modelo: 1 },
  regular: { categoría: 9, modelo: 3, regular: 1, tapered: 1 },
  tapered: { tapered: 3, categoría: 9, talle: 1, modelo: 1 },
  super: { modelo: 1 },
  tejido: { categoría: 18, tela: 19, deporte: 1, talle: 2 },
  zig: { categoría: 1 },
  zag: { categoría: 1 },
  joggers: { modelo: 13, talle: 1, categoría: 32, tamaño: 5 },
  "spider-man": { marca: 2, modelo: 1 },
  marvel: { género: 1, marca: 2 },
  true: { categoría: 2, marca: 1 },
  smart: { modelo: 1 },
  alpha: { modelo: 1 },
  desgastada: { categoría: 1 },
  jeggings: { categoría: 1 },
  doble: { categoría: 1, modelo: 1 },
  encaje: { categoría: 1 },
  "mount-strech": { modelo: 3 },
  detalle: { detalle: 2, deporte: 1, botón: 1 },
  elastico: { categoría: 7, modelo: 2, elástico: 2, diseño: 1 },
  lomena: { modelo: 1 },
  corte: {
    modelo: 25,
    categoría: 36,
    corte: 4,
    talle: 3,
    tamaño: 3,
  },
  straight: { modelo: 1, categoría: 2 },
  sport: { categoría: 1, deporte: 1 },
  satinado: { satinado: 2 },
  navy: { modelo: 2 },
  anchos: { talle: 1, categoría: 1 },
  vestir: { modelo: 3, categoría: 3 },
  coated: { categoría: 3 },
  kick: { categoría: 5 },
  conjunto: { categoría: 63, modelo: 1 },
  jersey: { categoría: 27 },
  spf: { marca: 56 },
  camisa: { categoría: 10 },
  sudadera: { categoría: 9 },
  lavado: {
    modelo: 23,
    categoría: 28,
    lavado: 6,
    tamaño: 1,
    marca: 2,
  },
  sostenible: { modelo: 5, marca: 2 },
  color: { color: 3, modelo: 5, categoría: 1 },
  shaping: { modelo: 1 },
  ajustado: { categoría: 2 },
  sarah: { modelo: 1 },
  resistentes: { categoría: 1 },
  agua: { deporte: 1, modelo: 1 },
  taper: { modelo: 1 },
  tiro: { tiro: 2, deporte: 10, modelo: 7, entrenamiento: 1 },
  alto: {
    alto: 25,
    deporte: 1,
    modelo: 2,
    largo: 2,
    categoría: 3,
    talle: 5,
    rendimiento: 1,
    tamaño: 2,
  },
  talle: {
    modelo: 1,
    largo: 4,
    "talle alto": 1,
    talle: 36,
    categoría: 3,
    tamaño: 3,
  },
  jegging: { categoría: 1 },
  leggins: { categoría: 1 },
  costuras: { deporte: 1 },
  moldeador: { modelo: 7, marca: 1 },
  culotte: { categoría: 3 },
  chaleco: { categoría: 1 },
  cazadora: { categoría: 2 },
  look: { modelo: 4 },
  hombre: { "género,edad": 16, género: 104, edad: 7, tamaño: 4 },
  blusa: { categoría: 2 },
  blazer: { categoría: 1 },
  bota: { categoría: 3 },
  guantes: { categoría: 1 },
  gorro: { categoría: 1 },
  chaqueta: { categoría: 2 },
  tejanero: { categoría: 1 },
  sobrecamisa: { categoría: 8 },
  panantalon: { categoría: 1 },
  relax: { relax: 1, modelo: 1, categoría: 1 },
  deportivo: {
    categoría: 10,
    modelo: 1,
    deporte: 13,
    talle: 1,
    tamaño: 1,
    túnica: 1,
  },
  bomber: { categoría: 1 },
  zapatilla: { categoría: 2 },
  camiseta: { categoría: 11 },
  pubjug: { categoría: 1 },
  camieta: { categoría: 1 },
  ensuciado: { categoría: 3 },
  cardigan: { categoría: 2 },
  zapato: { categoría: 1 },
  parka: { categoría: 4 },
  mujer: { "género,edad": 1, edad: 2, género: 67 },
  gorra: { categoría: 1 },
  micro: { tamaño: 1 },
  icono: { talle: 1 },
  vengadores: { talle: 1 },
  abrigo: { categoría: 1 },
  deportivas: { categoría: 1 },
  ligero: { categoría: 3 },
  verdoso: { categoría: 1 },
  ajustados: {
    talle: 3,
    categoría: 8,
    ajustados: 11,
    ajustado: 1,
    tamaño: 1,
    modelo: 4,
  },
  tobillo: { modelo: 1 },
  limpio: { deporte: 1, modelo: 1, talle: 1 },
  lisbon: { marca: 2 },
  asos: { marca: 98, modelo: 2 },
  design: { marca: 81, modelo: 14 },
  mom: { categoría: 12 },
  boot: { modelo: 1 },
  cut: { tamaño: 1 },
  comfort: { categoría: 2, modelo: 1 },
  knit: { modelo: 2, marca: 6 },
  monocromaticos: { modelo: 1 },
  azules: { categoría: 2 },
  claros: { categoría: 1 },
  pinza: { modelo: 1 },
  tobillero: { "tono negro": 1, categoría: 2 },
  cortos: { tamaño: 3, largo: 19, talle: 3, categoría: 1 },
  antirrozaduras: { antirrozaduras: 1 },
  maternity: { género: 1, modelo: 3 },
  chandal: { categoría: 21, talle: 14, marca: 3, modelo: 8 },
  capucha: { categoría: 2 },
  lazo: { modelo: 1 },
  "12,5": { tamaño: 1 },
  oz: { tamaño: 1, marca: 1 },
  rodillas: { tamaño: 1, modelo: 1 },
  rasgadas: { tamaño: 1, modelo: 1 },
  desgastado: { tamaño: 2, modelo: 4, desgastado: 1, efecto: 1 },
  drapeado: { categoría: 1 },
  rayas: { "género,edad": 1, categoría: 2, género: 1 },
  laterales: { "género,edad": 1 },
  basicos: { nudo: 1 },
  nudo: { modelo: 1 },
  negros: {
    categoría: 12,
    género: 1,
    ajustados: 1,
    tamaño: 1,
    modelo: 1,
    marca: 1,
  },
  anil: { categoría: 1, marca: 1 },
  raya: { "raya lateral": 1, categoría: 3, tamaño: 1, raya: 1 },
  lateral: { modelo: 2, categoría: 2, tamaño: 1, raya: 1 },
  city: { marca: 2, deporte: 1, entrenamiento: 1, modelo: 3 },
  pernera: { categoría: 8, pernera: 1 },
  ancha: { categoría: 4, ancha: 1 },
  finas: { categoría: 1 },
  white: { modelo: 1 },
  curve: { género: 2 },
  pliegues: { pliegues: 1 },
  delanteros: { detalle: 1 },
  trabilla: { botón: 1 },
  boton: { modelo: 1 },
  ultimate: { marca: 4 },
  tall: { tamaño: 4, género: 1, modelo: 3, talle: 2 },
  paneles: { categoría: 2 },
  cosidos: { categoría: 1 },
  serpiente: { serpiente: 1 },
  holgados: { talle: 2, categoría: 6, modelo: 3, tamaño: 1 },
  petite: { género: 6, tamaño: 1 },
  dad: { categoría: 1 },
  vintage: { vintage: 1, modelo: 1 },
  roturas: { roturas: 1, modelo: 1, marca: 1 },
  cadera: { categoría: 1 },
  cuero: { categoría: 1 },
  hebilla: { categoría: 1 },
  plateada: { marca: 1 },
  recta: { recta: 1, categoría: 2 },
  leopardo: { modelo: 1 },
  diseno: { diseño: 3, modelo: 3, marca: 1 },
  posiciones: { posiciones: 1 },
  rigidos: { categoría: 8 },
  clasicos: { modelo: 7, categoría: 3 },
  piedra: { modelo: 2, categoría: 1, marca: 1 },
  deportivos: { deporte: 2 },
  icon: { marca: 2, modelo: 2 },
  diplomatica: { categoría: 1, modelo: 1, "género,edad": 1 },
  realzador: { marca: 1 },
  beis: { modelo: 1 },
  hielo: { categoría: 2 },
  superpitillo: { categoría: 1, modelo: 1 },
  microtexturizado: { categoría: 2 },
  wedding: { modelo: 3 },
  acabado: { categoría: 1 },
  rotos: { rotos: 1, tamaño: 1 },
  patalones: { categoría: 1 },
  elegantes: { categoría: 2 },
  principe: { marca: 1 },
  gales: { género: 1 },
  banda: { categoría: 2, modelo: 1 },
  elasticos: { modelo: 3, categoría: 5, elásticos: 1 },
  caqui: { modelo: 2 },
  vientre: { modelo: 2 },
  "12.5": { modelo: 1 },
  rigido: { categoría: 1, modelo: 1 },
  campana: { categoría: 4, modelo: 1 },
  capri: { categoría: 1 },
  effortless: { marca: 1 },
  mblue: { marca: 2 },
  estilo: { modelo: 2, estilo: 2 },
  corto: {
    modelo: 2,
    largo: 31,
    categoría: 3,
    talle: 17,
    tamaño: 3,
  },
  spray: { modelo: 2 },
  on: { modelo: 2, marca: 1 },
  farleigh: { marca: 2 },
  autentico: { modelo: 1 },
  pack: { categoría: 5 },
  cm: { "secado rápido": 1, tamaño: 3, cm: 2 },
  secado: { deporte: 1 },
  rapido: { deporte: 1 },
  mezcla: { ajustados: 1, marca: 1 },
  lana: { lana: 3, tamaño: 1 },
  pata: { pata: 1 },
  gallo: { gallo: 1 },
  resistente: { categoría: 1, modelo: 2 },
  tobilleros: { categoría: 1 },
  anudada: { categoría: 1 },
  hourglass: { marca: 1, género: 1 },
  rasgados: { tamaño: 1 },
  marcados: { marca: 1 },
  lunares: { estampado: 1 },
  lino: { marca: 1 },
  grises: { categoría: 2 },
  pelillo: { categoría: 1 },
  texturizado: { categoría: 1 },
  intenso: { categoría: 1 },
  anos: { años: 1, modelo: 1, edad: 3 },
  envejecido: { categoría: 1 },
  entallados: { modelo: 2, categoría: 1 },
  estandar: { marca: 1, modelo: 1 },
  acolchados: { modelo: 1 },
  tenido: { modelo: 1 },
  retro: { modelo: 1 },
  poliuretano: { modelo: 1 },
  tintado: { modelo: 3 },
  clasico: { modelo: 1 },
  canale: { categoría: 1, marca: 1 },
  bajos: { categoría: 3, modelo: 1, bajos: 6 },
  ondulados: { categoría: 1 },
  abertura: { modelo: 1 },
  delantera: { modelo: 1, género: 1 },
  repelentes: { modelo: 1 },
  new: { marca: 6, modelo: 3, talle: 1 },
  action: { género: 1 },
  termicos: { categoría: 1 },
  ikar: { marca: 1 },
  logotipo: { marca: 2 },
  lima: { ciudad: 1 },
  golpe: { deporte: 1 },
  john: { marca: 1 },
  smith: { marca: 1, modelo: 6 },
  cital: { marca: 1 },
  nautica: { marca: 1 },
  kea: { marca: 1 },
  "+": { categoría: 1, modelo: 1 },
  infantil: { tamaño: 2, categoría: 7 },
  "100%": { material: 1 },
  poliester: { marca: 1 },
  love: { marca: 1 },
  fly: { marca: 1, modelo: 1 },
  trangoworld: { marca: 2 },
  altai: { modelo: 1 },
  th: { tamaño: 1 },
  esqui: { deporte: 23 },
  forno: { deporte: 1 },
  impermeable: { modelo: 2, deporte: 5, categoría: 1 },
  nino: {
    categoría: 1,
    edad: 32,
    tamaño: 5,
    género: 10,
    "género,edad": 3,
  },
  puma: { marca: 23 },
  "essentials+": { modelo: 1 },
  col: { modelo: 1 },
  lady: { género: 1 },
  loop: { modelo: 1 },
  ombre: { marca: 1 },
  pirata: { categoría: 1, talle: 1 },
  yoga: { categoría: 1, deporte: 1, talle: 1, género: 1 },
  embarazada: { categoría: 1, tamaño: 1, género: 1 },
  ecofriendly: { categoría: 1, marca: 2 },
  sobrepantalon: { categoría: 3 },
  sailing: { modelo: 1 },
  ninos: {
    deporte: 2,
    género: 6,
    "género,edad": 2,
    edad: 1,
    categoría: 2,
  },
  lluvia: { deporte: 1 },
  nieve: { deporte: 18 },
  "7-15": { edad: 1 },
  wedze: { marca: 10 },
  "ski-p": { marca: 1, modelo: 2 },
  pa: { marca: 1 },
  alpinismo: { deporte: 1 },
  montana: { deporte: 1, categoría: 1 },
  simond: { marca: 2 },
  alpinism: { modelo: 1 },
  light: { modelo: 2 },
  evo: { modelo: 1 },
  termico: {
    categoría: 6,
    talle: 1,
    térmico: 5,
    tela: 1,
    tamaño: 1,
  },
  interior: { categoría: 5, interior: 9, deporte: 1, modelo: 1 },
  fr900: { marca: 2 },
  origin: { marca: 5, modelo: 1 },
  junior: { edad: 19, modelo: 1, deporte: 1, tamaño: 7 },
  padelpersonalizable: { deporte: 2 },
  padel: { modelo: 4, deporte: 9 },
  personalizable: { modelo: 3, deporte: 1 },
  cremallera: { cremallera: 11 },
  jogging: { categoría: 1, modelo: 1 },
  fitness: { modelo: 1, deporte: 3, categoría: 3 },
  adidas: { marca: 66 },
  core: { modelo: 1 },
  lounge: { modelo: 1 },
  asics: { marca: 1 },
  logo: { modelo: 6, marca: 3 },
  blanco: { tamaño: 7, modelo: 2, tonalidad: 1 },
  short: { categoría: 1, talle: 1, modelo: 2 },
  transpirable: { deporte: 3 },
  equitacion: { competición: 1, categoría: 3 },
  competicion: { deporte: 2 },
  fouganza: { marca: 2, modelo: 1, categoría: 1 },
  caza: { categoría: 8 },
  solognac100: { marca: 1 },
  camuflaje: { modelo: 5 },
  tirantes: { tira: 1, modelo: 1 },
  "6-14": { edad: 2 },
  pa500: { tamaño: 1 },
  solognac: { marca: 7 },
  halftone: { modelo: 1 },
  calido: { modelo: 3, deporte: 1, categoría: 1 },
  polar: { modelo: 2 },
  "wed'ze": { marca: 1 },
  bl: { modelo: 2 },
  seamless: { deporte: 1 },
  baloncesto: { deporte: 6 },
  tarmak: { marca: 1 },
  sh900: { modelo: 1 },
  futbol: { deporte: 32, talle: 4 },
  kipsta: { marca: 2 },
  viralto: { marca: 2 },
  fluor: { tamaño: 1 },
  sgtr: { marca: 1 },
  reforzado: { modelo: 1 },
  marron: { modelo: 1, tamaño: 1 },
  tiempo: { modelo: 1 },
  seco: { modelo: 1 },
  sublimado: { deporte: 1 },
  rugby: { deporte: 8 },
  merina: { deporte: 2 },
  ciclismo: { deporte: 3, talle: 1 },
  mtb: { deporte: 2 },
  rockrider: { marca: 2 },
  race: { modelo: 4 },
  personalizado: { deporte: 7, edad: 2, modelo: 1 },
  adulto: { edad: 13, género: 3, tamaño: 1 },
  trekking: { categoría: 2 },
  desierto: { modelo: 1 },
  upf40: { marca: 1 },
  forclaz: { marca: 1 },
  desert: { modelo: 1 },
  f540: { modelo: 1 },
  bl900: { modelo: 1 },
  falda: { categoría: 3 },
  golf: { deporte: 3 },
  ww500: { marca: 1, modelo: 1 },
  ski: { modelo: 1 },
  shorts: { talle: 1, tamaño: 1 },
  inesis: { marca: 1 },
  steppe: { marca: 1 },
  multibolsillos: { modelo: 1 },
  escalada: { deporte: 1 },
  ski580: { modelo: 2 },
  marismas: { modelo: 1 },
  bullpadel: { marca: 1 },
  llano: { modelo: 1 },
  kimjaly: { marca: 1 },
  ladovy: { modelo: 1 },
  squadra: { modelo: 2 },
  st: { modelo: 2 },
  voley: { deporte: 3 },
  ninas: { género: 1 },
  domyos: { marca: 2 },
  essentials: { modelo: 5 },
  badanas: { tamaño: 1 },
  adherentes: { tamaño: 1 },
  concurso: { modelo: 1 },
  voleibol: { deporte: 1 },
  allsix: { marca: 1 },
  v100: { modelo: 1 },
  fondo: { deporte: 7 },
  inovik: { marca: 6 },
  utilitario: { modelo: 1 },
  xc: { modelo: 5, deporte: 1 },
  s: { deporte: 3, tamaño: 1, marca: 1 },
  uw: { deporte: 2, modelo: 1 },
  cardio: { modelo: 1 },
  sereno: { modelo: 6, tamaño: 1 },
  pt: { tamaño: 1, modelo: 1 },
  s500: { deporte: 1 },
  tecnico: { tamaño: 1 },
  pesca: { categoría: 1 },
  submarina: { categoría: 1 },
  neopreno: { tamaño: 1 },
  mm: { tamaño: 1 },
  warm: { categoría: 1 },
  bicicleta: { modelo: 1 },
  ciudad: { género: 1 },
  cubrecalzado: { modelo: 1 },
  integrado: { modelo: 1 },
  urbano: { deporte: 1 },
  btwin: { marca: 1 },
  swix: { marca: 2 },
  badminton: { deporte: 1 },
  perfly: { marca: 1 },
  m: { modelo: 1 },
  own: { deporte: 1 },
  the: { deporte: 1, marca: 7, modelo: 1 },
  run: { deporte: 1 },
  modelo: { marca: 1, modelo: 1 },
  cup: { modelo: 2 },
  personalizada: { marca: 1 },
  "ski-p500": { modelo: 1 },
  softshell: { modelo: 1 },
  silencioso: { modelo: 2 },
  sigilo: { modelo: 1 },
  balonmano: { deporte: 1 },
  bosque: { modelo: 1 },
  nike: { marca: 113, modelo: 4 },
  club: { modelo: 6, deporte: 1, categoría: 4 },
  con20: { modelo: 1 },
  dry: { modelo: 1 },
  get: { modelo: 1 },
  tiro19: { deporte: 1 },
  casual: { talle: 8, categoría: 13, tente: 3, tamaño: 5 },
  frontales: { "pinzas frontales": 1 },
  edit: { marca: 1 },
  evostripe: { deporte: 1 },
  tenth: {
    modelo: 18,
    tente: 3,
    tamaño: 10,
    deporte: 2,
    marca: 1,
    edad: 1,
    categoría: 4,
    talle: 1,
  },
  neofleece: { marca: 1 },
  tie: { tente: 1 },
  dye: { deporte: 1 },
  nina: { edad: 5, género: 2, tamaño: 1 },
  swoosh: { deporte: 1, marca: 1 },
  sq21: { modelo: 1 },
  b: { modelo: 3 },
  "3s": { deporte: 1, tamaño: 2, modelo: 2 },
  balance: { marca: 1, modelo: 3 },
  "dri-fit": { deporte: 7, modelo: 5, marca: 14, tamaño: 1 },
  academy: { deporte: 2, categoría: 6 },
  ess: { modelo: 5 },
  big: { tamaño: 1 },
  kids: { tamaño: 1 },
  slouchy: { tamaño: 1 },
  champion: { marca: 2 },
  legacy: { modelo: 2 },
  print: { tamaño: 2 },
  training: {
    tamaño: 3,
    talle: 4,
    modelo: 4,
    tenth: 2,
    tape: 1,
    deporte: 1,
  },
  costura: { modelo: 1 },
  snow: { tamaño: 1 },
  unisex: { género: 1 },
  cuff: { modelo: 1 },
  essential: { modelo: 4 },
  seam: { modelo: 1 },
  zurito: { deporte: 1, modelo: 2 },
  reflector: { deporte: 1 },
  cortes: { tamaño: 1 },
  pato: { modelo: 1 },
  donald: { modelo: 1 },
  disney: { marca: 7, género: 2 },
  fleece: {
    deporte: 2,
    modelo: 21,
    marca: 1,
    categoría: 5,
    tamaño: 1,
    talle: 1,
  },
  externos: { deporte: 1 },
  youth: { edad: 1 },
  texturas: { tente: 1, tono: 1 },
  contraste: { deporte: 1 },
  estrecho: { tamaño: 1, talle: 12, modelo: 11, categoría: 2 },
  malla: { tamaño: 1, "malla interior": 3 },
  pipping: { tamaño: 1 },
  fl: { modelo: 1 },
  tc: { modelo: 1 },
  "ess+tape": { tapa: 1 },
  sweatpants: { tamaño: 1, modelo: 1 },
  exclusivo: { modelo: 1 },
  decimas: { modelo: 1 },
  colorblock: { modelo: 2 },
  ned: { género: 1 },
  gray: { tamaño: 1 },
  heather: { tamaño: 1 },
  tape: { modelo: 3, tamaño: 1 },
  puno: { categoría: 1 },
  basic: { modelo: 2 },
  embroidery: { marca: 2 },
  power: { modelo: 5 },
  repeat: { modelo: 1 },
  feelcozy: { modelo: 1, deporte: 1 },
  mel: { modelo: 1 },
  college: { modelo: 1 },
  solid: { modelo: 1 },
  bloques: { marca: 1 },
  open: { género: 1, modelo: 1 },
  techfleece: { tela: 1 },
  american: { tamaño: 1 },
  cremalleras: { cremallera: 1 },
  "high-waist": { talle: 1 },
  monocolor: { modelo: 1 },
  all: { modelo: 1, tamaño: 2 },
  szn: { modelo: 1, tamaño: 1 },
  fred: { marca: 1 },
  perry: { marca: 1 },
  classic: { modelo: 1 },
  swim: { modelo: 1 },
  "levi's": { marca: 14 },
  baggy: { modelo: 1 },
  pants: {
    categoría: 14,
    deporte: 3,
    tamaño: 1,
    modelo: 16,
    talle: 1,
  },
  tommy: { marca: 2 },
  velour: { modelo: 2 },
  bandeau: { modelo: 1 },
  bralette: { modelo: 1, categoría: 1 },
  jean: { categoría: 70, modelo: 11, talle: 4, tamaño: 1 },
  cenido: { categoría: 13, cónico: 5, modelo: 3, tamaño: 2 },
  bootcut: { modelo: 5 },
  manchester: { modelo: 1, entrenamiento: 1, categoría: 1, marca: 1 },
  fc: { deporte: 2, modelo: 4 },
  track: { deporte: 3, tamaño: 1, modelo: 16, categoría: 3 },
  originals: { modelo: 1, tape: 1, categoría: 2 },
  adicolor: { categoría: 2, modelo: 8 },
  sst: { deporte: 1, modelo: 3 },
  entrenamiento: { entrenamiento: 4, deporte: 1 },
  united: { entrenamiento: 1, modelo: 1, marca: 1 },
  montirex: { marca: 2 },
  "2.0": { tamaño: 1 },
  lacoste: { marca: 2 },
  graphic: { modelo: 1 },
  croc: { modelo: 1 },
  "therma-fit": { talle: 1, deporte: 1, modelo: 4 },
  dna: { modelo: 2 },
  chelsea: { marca: 1 },
  strike: { modelo: 8, marca: 1 },
  tallas: { tamaño: 3 },
  aeroready: { talle: 1 },
  stanford: { género: 1 },
  hem: { modelo: 1 },
  embroidered: { modelo: 1 },
  small: { tamaño: 1, modelo: 1 },
  "2023/24": { año: 1, modelo: 2 },
  third: { categoría: 1 },
  jordan: { marca: 10 },
  nba: { marca: 1, deporte: 9 },
  york: { marca: 1 },
  knicks: { marca: 1 },
  swingman: { modelo: 1, deporte: 3, talle: 1 },
  girls: { categoría: 1 },
  tech: { categoría: 1 },
  storm: { modelo: 1 },
  outdoor: { deporte: 1, categoría: 1 },
  air: { modelo: 24, marca: 7 },
  max: { categoría: 2 },
  nicce: { marca: 2 },
  sports: { modelo: 1 },
  north: { marca: 5 },
  face: { marca: 5 },
  glacier: { modelo: 1 },
  ampere: { modelo: 1 },
  oversized: { modelo: 1 },
  combat: { modelo: 2 },
  under: { marca: 1 },
  armour: { marca: 1, modelo: 1 },
  ua: { modelo: 1 },
  athletic: { categoría: 1, modelo: 1 },
  future: { modelo: 1 },
  icons: { modelo: 1 },
  supply: { categoría: 3, marca: 1 },
  demand: { categoría: 3, marca: 1 },
  alight: { modelo: 1 },
  woven: { modelo: 3, categoría: 11, tela: 2 },
  mountain: { modelo: 2 },
  athletics: { modelo: 2 },
  lab: { modelo: 1 },
  classics: { modelo: 7 },
  beckenbauer: { modelo: 3 },
  suecia: { género: 1 },
  mckenzie: { marca: 3, categoría: 1 },
  moran: { marca: 1 },
  poly: { modelo: 1, categoría: 1 },
  arid: { modelo: 1 },
  miles: { "género,edad": 1 },
  morales: { marca: 1 },
  juventus: { modelo: 1 },
  designed: { modelo: 2 },
  for: { gameday: 1 },
  gameday: { gameday: 1, deporte: 1 },
  alemania: { modelo: 1 },
  primeblue: { categoría: 1 },
  byrant: { marca: 1 },
  fine: { modelo: 1 },
  box: { modelo: 1 },
  reebok: { marca: 2, categoría: 1 },
  identity: { modelo: 1 },
  french: { tamaño: 1, tela: 2, categoría: 1 },
  terry: { tamaño: 1, tela: 2, categoría: 1 },
  adibreak: { modelo: 3 },
  hoodrich: { marca: 5, talle: 1 },
  castore: { marca: 2 },
  newcastle: { marca: 1 },
  travel: { modelo: 2 },
  "3-pack": { modelo: 1 },
  lace: { modelo: 1 },
  thongs: { modelo: 1 },
  cealus: { marca: 1 },
  olympique: { marca: 1 },
  marseille: { marca: 1 },
  lane: { categoría: 1 },
  celtic: { deporte: 1 },
  adolescentes: { edad: 12 },
  indi: { modelo: 1 },
  cr: { categoría: 1 },
  flamengo: { modelo: 1 },
  teamgeist: { modelo: 1 },
  wolverhampton: { marca: 1 },
  wanderers: { marca: 1 },
  jnr: { tamaño: 1 },
  presentacion: { modelo: 1 },
  japan: { deporte: 1 },
  peak: { modelo: 1 },
  wash: { modelo: 1 },
  converse: { marca: 1 },
  chuck: { modelo: 1 },
  taylor: { modelo: 1 },
  metallic: { modelo: 1 },
  oskar: { marca: 1 },
  alessandro: { marca: 1 },
  zavetti: { marca: 1 },
  mazzola: { marca: 1 },
  linear: { categoría: 1 },
  deflect: { modelo: 1 },
  arch: { modelo: 1 },
  duffer: { marca: 1 },
  of: { modelo: 1 },
  george: { modelo: 1 },
  standard: { modelo: 4 },
  children: { género: 1 },
  calvin: { marca: 2 },
  klein: { marca: 2 },
  modern: { modelo: 1 },
  cotton: { modelo: 1 },
  wales: { modelo: 1 },
  oblique: { modelo: 1 },
  over: { tamaño: 1 },
  area: { categoría: 2 },
  running: { marca: 1, deporte: 3 },
  active: { modelo: 1 },
  hugo: { marca: 1 },
  barcelona: { modelo: 1, marca: 1 },
  teech: { modelo: 1 },
  technicals: { categoría: 1 },
  volta: { modelo: 1 },
  issue: { categoría: 2, modelo: 1 },
  paris: { marca: 1 },
  saint: { marca: 1 },
  germain: { marca: 1 },
  berghaus: { marca: 1 },
  hike: { modelo: 2 },
  juicy: { marca: 1 },
  couture: { marca: 1 },
  diamante: { modelo: 1 },
  mercier: { marca: 1 },
  kansas: { modelo: 1 },
  trefoil: { modelo: 1 },
  "®": { marca: 22, modelo: 7 },
  conico: { categoría: 2, cónico: 5, modelo: 8, tamaño: 1 },
  superestrecho: { talle: 7, modelo: 3, categoría: 1 },
  mile: { modelo: 4 },
  ribcage: { modelo: 2 },
  ajuste: { modelo: 8, categoría: 2 },
  rectos: { tamaño: 2 },
  wedgie: { modelo: 2 },
  plus: { modelo: 1 },
  recortado: { categoría: 2 },
  "hi-ball": { modelo: 1 },
  roll: { modelo: 1 },
  cenidos: { categoría: 3 },
  acampanados: { talle: 1 },
  minnie: { "género,edad": 1, marca: 1 },
  mouse: { marca: 3 },
  supercenidos: { categoría: 1 },
  made: { marca: 2 },
  crafted: { marca: 2 },
  pijama: { categoría: 10 },
  kem: { marca: 2 },
  column: { categoría: 1 },
  muslo: { modelo: 1 },
  popelina: { categoría: 1 },
  estampados: { bocetos: 1, modelo: 1 },
  bocetos: { bocetos: 1 },
  daisy: { marca: 2 },
  angel: { categoría: 1 },
  paracaidista: { categoría: 2 },
  rita: { "género,edad": 1, marca: 2 },
  ora: { marca: 2, género: 1 },
  set: { categoría: 2 },
  entallado: { categoría: 5, modelo: 1 },
  grafico: { modelo: 2, estampado: 1 },
  unstopabble: { modelo: 2 },
  antidesgarros: { deporte: 1 },
  panel: { categoría: 1 },
  otomano: { género: 1 },
  jaspeados: { tamaño: 1, talle: 1 },
  rendimiento: { rendimiento: 1 },
  boxer: { modelo: 1 },
  corazones: { modelo: 1 },
  mickey: { marca: 1 },
  revestimiento: { revestimiento: 1 },
  conica: { categoría: 1 },
  calidos: { categoría: 1 },
  cobra: { marca: 1 },
  kai: { marca: 1 },
  tacto: { categoría: 1 },
  suave: { categoría: 1 },
  flores: { categoría: 1 },
  strass: { "género,edad": 1 },
  sirsaca: { categoría: 1 },
  lentejuelas: { categoría: 1 },
  arrugado: { arrugado: 1 },
  acg: { marca: 33 },
  trail: { deporte: 3, tamaño: 1 },
  polartec: { marca: 5 },
  wolf: { género: 1, modelo: 4, marca: 2 },
  tree: { tamaño: 1, modelo: 4, marca: 2 },
  "storm-fit": { modelo: 2 },
  rope: { modelo: 1 },
  dope: { modelo: 1 },
  summit: { modelo: 6 },
  transformable: { categoría: 2, deporte: 1 },
  militar: { "género,edad": 1 },
  adv: { deporte: 2, tamaño: 1, entrenamiento: 1 },
  aeroswift: { modelo: 1, categoría: 1 },
  body: { categoría: 1 },
  pastel: { modelo: 1 },
  juego: { categoría: 1, modelo: 1 },
  mariposa: { categoría: 1 },
  acido: { categoría: 1 },
  anilla: { categoría: 1, anilla: 1 },
  d: { modelo: 1 },
  sarga: { categoría: 3 },
  combinables: { modelo: 2 },
  colores: { modelo: 1 },
  angeles: { marca: 2 },
  lakers: { marca: 2 },
  basquiat: { modelo: 1 },
  moldeadores: { modelo: 1 },
  winnie: { marca: 1 },
  pooh: { marca: 1 },
  cuello: { categoría: 1 },
  polo: { categoría: 1 },
  borrego: { categoría: 1 },
  sintetica: { marca: 1 },
  barbie: { marca: 1 },
  movie: { género: 1 },
  destenidos: { modelo: 1 },
  canyon: { modelo: 1 },
  farer: { modelo: 1 },
  botines: { categoría: 1 },
  premama: { categoría: 1 },
  k: { modelo: 1 },
  winter: { categoría: 1 },
  warrior: { modelo: 1 },
  cinder: { modelo: 1 },
  cone: { modelo: 1 },
  cortavientos: { modelo: 1 },
  sands: { modelo: 2, tamaño: 1 },
  senderismo: { deporte: 2 },
  x: { modelo: 1, categoría: 1 },
  titan: { modelo: 1 },
  wordmark: { modelo: 6 },
  pequeno: { tamaño: 1, edad: 1 },
  printed: { tamaño: 1 },
  repel: { modelo: 2 },
  convertible: { tamaño: 1 },
  one: { talle: 1 },
  snowgrass: { modelo: 1 },
  "a.p.s.": { tamaño: 1, categoría: 3 },
  ready: { entrenamiento: 1 },
  marcus: { categoría: 1 },
  rashford: { "género,edad": 1 },
  inglaterra: { marca: 5 },
  versatil: { modelo: 3 },
  atlanta: { marca: 1 },
  hawks: { marca: 1 },
  edition: { modelo: 5 },
  atletico: { marca: 7 },
  madrid: { marca: 7 },
  attack: { modelo: 1 },
  forro: { deporte: 1 },
  australia: { marca: 1 },
  bliss: { talle: 2 },
  boston: { marca: 6 },
  celtics: { marca: 6 },
  showtime: { marca: 1, modelo: 1 },
} as LabelMap
