[tool.poetry]
name = "site"
version = "0.1.0"
description = ""
authors = ["Antonio Sánchez <sago.ant@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sentence-transformers = "^2.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
