[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "3.11.2"
spacy = {version = "3.7.5", extras = ["cuda11x"]}
es-core-news-sm = {url = "https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.7.0/es_core_news_sm-3.7.0-py3-none-any.whl"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
