[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9.2"
sentence-transformers = "^2.5.1"
spacy = {extras = ["cuda11x"], version = "^3.7.4"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
