[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9.2"
sentence-transformers = "^2.5.1"
rake-nltk = "^1.0.6"
spacy = {extras = ["cuda11x"], version = "^3.7.4"}
es-core-news-sm = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
