[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9.2"
sentence-transformers = "^2.5.1"
rake-nltk = "^1.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
