[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "3.9.2"
transformers = {extras = ["torch"], version = "4.41.2"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
