export const Equals = Symbol("Key-Value assignment")
export const ValueSeparator = Symbol("Value separator")
export const PropertyEnd = Symbol("Property end")
export const EntityStart = Symbol("Entity start")
export const EntityEnd = Symbol("Entity end")
